### ISSUE TITLE
Git Clone causing VS to crash

### ISSUE THREAD

**Issue by tierninho** [github/VisualStudio#1064]
When trying to clone a repo in the GitHub window, my VS keeps crashing. While repos list is loading, try interacting with it, like enter a repo to search.

Ext. v2.3.0.0, Windows 10, VS 2017

<img width="652" alt="screen shot 2017-07-12 at 1 17 38 pm" src="https://user-images.githubusercontent.com/14828183/28130428-91691cf8-6704-11e7-8ba8-7e0d59b51960.png">

LOGS:
System.ArgumentNullException occurred
  HResult=0x80004003
  Message=Value cannot be null.
  Source=mscorlib
  StackTrace:
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Akavache.InMemoryBlobCache.InsertObject[T](String key, T value, Nullable`1 absoluteExpiration)
   at Akavache.JsonSerializationMixin.InsertObject[T](IBlobCache This, String key, T value, Nullable`1 absoluteExpiration)
   at GitHub.Caches.CacheIndex.Save(IBlobCache cache, Nullable`1 absoluteExpiration) in C:\Users\atom\Source\Repos\VisualStudio\src\GitHub.App\Caches\CacheIndex.cs:line 76
   at GitHub.Extensions.AkavacheExtensions.<>c__DisplayClass4_0`1.<<GetAndFetchLatestFromIndex>b__13>d.MoveNext() in C:\Users\atom\Source\Repos\VisualStudio\src\GitHub.App\Extensions\AkavacheExtensions.cs:line 231
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

<img width="274" alt="screen shot 2017-07-12 at 1 14 34 pm" src="https://user-images.githubusercontent.com/14828183/28130204-21221454-6704-11e7-9b0e-4f4defb8d11f.png">

**Comment by grokys** [comment]
Seems to be a threading issue: `ViewBase.IsBusy` is being set from `RepositoryCloneViewModel.cs:136` from a non-UI thread.
