### ISSUE TITLE
Unable to install on Visual Studio Express 2015

### ISSUE THREAD

**Issue by jfgossage** [github/VisualStudio#1167]
I am attempting to install the GitHub Extension for Visual Studio 2.3.0.20 in a brand new copy of Visual Studio Express 2015 running on Windows 8.1.

The VSIX installer says that this extension is not installable on any currently installed products. The install log follows:

2017-08-18 8:09:06 PM - Microsoft VSIX Installer
2017-08-18 8:09:06 PM - -------------------------------------------
2017-08-18 8:09:06 PM - Initializing Install...
2017-08-18 8:09:06 PM - Extension Details...
2017-08-18 8:09:06 PM - 	Identifier         : c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
2017-08-18 8:09:06 PM - 	Name               : GitHub Extension for Visual Studio
2017-08-18 8:09:06 PM - 	Author             : GitHub, Inc
2017-08-18 8:09:06 PM - 	Version            : 2.2.0.11
2017-08-18 8:09:06 PM - 	Description        : A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
2017-08-18 8:09:06 PM - 	Locale             : en-US
2017-08-18 8:09:06 PM - 	MoreInfoURL        : https://visualstudio.github.com/
2017-08-18 8:09:06 PM - 	InstalledByMSI     : False
2017-08-18 8:09:06 PM - 	SupportedFrameworkVersionRange : [4.5,)
2017-08-18 8:09:06 PM - 
2017-08-18 8:09:07 PM - 	SignatureState     : ValidSignature
2017-08-18 8:09:07 PM - 	SignedBy           : GitHub, Inc.
2017-08-18 8:09:07 PM - 	Certificate Info   : 
2017-08-18 8:09:07 PM - 		-------------------------------------------------------
2017-08-18 8:09:07 PM - 		[Subject]       : CN="GitHub, Inc.", O="GitHub, Inc.", L=San Francisco, S=California, C=US
2017-08-18 8:09:07 PM - 		[Issuer]        : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
2017-08-18 8:09:07 PM - 		[Serial Number] : 013AA7BBB950DCCD25305F1602258B00
2017-08-18 8:09:07 PM - 		[Not Before]    : 2016-11-22 6:00:00 PM
2017-08-18 8:09:07 PM - 		[Not After]     : 2019-11-19 6:00:00 AM
2017-08-18 8:09:07 PM - 		[Thumbprint]    : C4FDF13659F49E57AC14774FDF45053F499F185F
2017-08-18 8:09:07 PM - 
2017-08-18 8:09:07 PM - 	Supported Products : 
2017-08-18 8:09:07 PM - 		Microsoft.VisualStudio.Community
2017-08-18 8:09:07 PM - 			Version : [14.0,15.0]
2017-08-18 8:09:07 PM - 
2017-08-18 8:09:07 PM - 	References         : 
2017-08-18 8:09:07 PM - 		-------------------------------------------------------
2017-08-18 8:09:07 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
2017-08-18 8:09:07 PM - 		Name         : Visual Studio MPF 14.0
2017-08-18 8:09:07 PM - 		Version      : [14.0,)
2017-08-18 8:09:07 PM - 		MoreInfoURL  : 
2017-08-18 8:09:07 PM - 		Nested       : No
2017-08-18 8:09:07 PM - 
2017-08-18 8:09:07 PM - Signature Details...
2017-08-18 8:09:07 PM - 	Extension is signed with a valid signature.
2017-08-18 8:09:07 PM - 
2017-08-18 8:09:07 PM - Searching for applicable products...
2017-08-18 8:09:07 PM - Found installed product - Microsoft Visual Studio Express 2015 for Windows Desktop
2017-08-18 8:09:07 PM - Found installed product - Global Location
2017-08-18 8:09:07 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Can you say what SKU's are necessary for this extension to install?

**Comment by grokys** [comment]
Hi @jfgossage,

The Visual Studio Express SKU [doesn't allow installing 3rd part extensions](https://visualstudiomagazine.com/articles/2014/05/21/no-extensions-for-visual-studio-express.aspx).

I'd advise using the Visual Studio Community edition: https://www.visualstudio.com/vs/community/ if possible. This is free (with limitations - see the Usage section on the page) and supports extensions.
