### ISSUE TITLE
Git operation trying to use SSH protocol and failing

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#1171]
- GitHub Extension for Visual Studio version: 2.3.0.20
- Visual Studio version: VS2015

From @shana:

Earlier today:

```
2017-08-03 16:29:53.7711|ERROR|thread:54|GitClient|Failed to fetch
LibGit2Sharp.LibGit2SharpException: Unsupported URL protocol
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteSafeHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
   at LibGit2Sharp.Network.DoFetch(FetchOptions options, RemoteSafeHandle remoteHandle, String logMessage, IEnumerable`1 refspecs)
   at LibGit2Sharp.Network.DoFetch(RepositorySafeHandle repoHandle, Remote remote, FetchOptions options, String logMessage, IEnumerable`1 refspecs)
   at LibGit2Sharp.Network.Fetch(Remote remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
   at LibGit2Sharp.Network.Fetch(Remote remote, IEnumerable`1 refspecs, FetchOptions options)
   at GitHub.Services.GitClient.<>c__DisplayClass8_0.<Fetch>b__0() in D:\code\github\VisualStudio\src\GitHub.App\Services\GitClient.cs:line 97    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteSafeHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
   at LibGit2Sharp.Network.DoFetch(FetchOptions options, RemoteSafeHandle remoteHandle, String logMessage, IEnumerable`1 refspecs)
   at LibGit2Sharp.Network.DoFetch(RepositorySafeHandle repoHandle, Remote remote, FetchOptions options, String logMessage, IEnumerable`1 refspecs)
   at LibGit2Sharp.Network.Fetch(Remote remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
   at LibGit2Sharp.Network.Fetch(Remote remote, IEnumerable`1 refspecs, FetchOptions options)
```

That means that something is calling GitClient with an ssh url and it's not falling back to using the https equivalent

**Comment by grokys** [comment]
I've been unable to repro this in a SSH repository. As far as I can see all calls to `GitClient.Fetch` use the https equivalent remote. Any idea what you were doing at the time @shana? Is this the full stacktrace from the log?
