### ISSUE TITLE
team explorer crash

### ISSUE THREAD

**Issue by DrYSG** [github/VisualStudio#129]
I have been using VS2015 with a locally hosted git project for several months successfully. In the middle of the day it stopped working. When I go to the home tab for the Team Explorer, I see the following errors:

```
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection". ---> System.Exception: The component 'GitHub.VisualStudio.UI.Views.GitHubHomeContent' does not have a resource identified by the URI '/GitHub.VisualStudio;component/ui/views/githubhomecontent.xaml'.
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at GitHub.VisualStudio.UI.Views.GitHubHomeContent.InitializeComponent() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\UI\Views\GitHubHomeContent.xaml:line 1
   at GitHub.VisualStudio.UI.Views.GitHubHomeContent..ctor() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\UI\Views\GitHubHomeContent.xaml.cs:line 15
   at GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection..ctor(ISimpleApiClientFactory apiFactory, ITeamExplorerServiceHolder holder) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\TeamExplorer\Home\GitHubHomeSection.cs:line 27
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass4`2.<CreateStronglyTypedExportFactoryOfTM>b__5()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```

**Comment by DrYSG** [comment]
Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA114
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA114
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA114
Microsoft Visual C++ 2015

AnkhSVN - Subversion Support for Visual Studio   2.5.12703.45
AnkhSVN - Subversion Support for Visual Studio 2.5.12703.45 
 * Ankh.Package 2.5.12703.45
 * Subversion 1.8.13 via SharpSvn 1.8013.3694.107

SharpSvn is linked to: Apr 1.5.1, Apr-util 1.5.4, Cyrus Sasl 2.1.25, eXpat 2.1.0, OpenSSL 1.0.2d 9 Jul 2015, serf 1.3.8, SQLite 3.7.17, Subversion 1.8.13-SharpSvn-1.8.13, ZLib 1.2.8
SharpSvn is optionally linked to: Berkeley DB 4.4.20, SharpPlink 0.64.0(SharpSvn)

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   14.0.20711.0
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.6
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

File Nesting   1.0
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure HDInsight HQL Service   2.0.2600.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2600.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Node.js Tools   1.1.30716.01
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.30716.01
Profiling support for Node.js projects.

NuGet Package Manager   3.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

**Comment by shana** [comment]
Can you tell me what is the full version of the GitHub extension? You can see it Tools / Extensions and Updates. Did you update the extension right before this started happening?

**Comment by prasethu** [comment]
The version is 1.0.15.2

The user saw the notification, updated the extension to the version above and then started seeing the issue.

**Comment by DrYSG** [comment]
version 1..0.15.2


I am trying to update it, and I shut down everything I can think of (and unblocked the VSIX file, and still I get this error. Right now, I am not using GitHub, so I would be happy if I could remove the extension (but it complains about that also). We have a local git server and that is what I am using, but this in interfering with that.

```
10/13/2015 4:20:16 PM - Microsoft VSIX Installer
10/13/2015 4:20:16 PM - -------------------------------------------
10/13/2015 4:20:16 PM - Initializing Install...
10/13/2015 4:20:16 PM - Extension Details...
10/13/2015 4:20:16 PM - 	Identifier      : c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
10/13/2015 4:20:16 PM - 	Name            : GitHub Extension for Visual Studio
10/13/2015 4:20:16 PM - 	Author          : GitHub, Inc
10/13/2015 4:20:16 PM - 	Version         : 1.0.15.2
10/13/2015 4:20:16 PM - 	Description     : A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
10/13/2015 4:20:16 PM - 	Locale          : en-US
10/13/2015 4:20:16 PM - 	MoreInfoURL     : https://visualstudio.github.com/
10/13/2015 4:20:16 PM - 	InstalledByMSI  : False
10/13/2015 4:20:16 PM - 	SupportedFrameworkVersionRange : [4.5,)
10/13/2015 4:20:16 PM - 
10/13/2015 4:20:17 PM - 	SignedBy        : GitHub, Inc
10/13/2015 4:20:17 PM - 	Certificate Info : [Subject]
  CN="GitHub, Inc", OU=Digital ID Class 3 - Microsoft Software Validation v2, O="GitHub, Inc", L=San Francisco, S=California, C=US

[Issuer]
  CN=VeriSign Class 3 Code Signing 2010 CA, OU=Terms of use at https://www.verisign.com/rpa (c)10, OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US

[Serial Number]
  2EA078CF4DAE81459313B225E26B568B

[Not Before]
  3/7/2013 7:00:00 PM

[Not After]
  6/6/2016 7:59:59 PM

[Thumbprint]
  C5C87FB961A2318109A5A87561C9E90923685ED6

10/13/2015 4:20:17 PM - 	Supported Products : 
10/13/2015 4:20:17 PM - 		Microsoft.VisualStudio.Community
10/13/2015 4:20:17 PM - 			Version : [14.0,)
10/13/2015 4:20:17 PM - 
10/13/2015 4:20:17 PM - 	References      : 
10/13/2015 4:20:17 PM - 		-------------------------------------------------------
10/13/2015 4:20:17 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
10/13/2015 4:20:17 PM - 		Name         : Visual Studio MPF 14.0
10/13/2015 4:20:17 PM - 		Version      : [14.0]
10/13/2015 4:20:17 PM - 		MoreInfoURL  : 
10/13/2015 4:20:17 PM - 		Nested       : No
10/13/2015 4:20:17 PM - 
10/13/2015 4:20:17 PM - 
10/13/2015 4:20:17 PM - Searching for applicable products...
10/13/2015 4:20:17 PM - Found installed product - Microsoft Visual Studio Professional 2013
10/13/2015 4:20:17 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
10/13/2015 4:20:17 PM - Found installed product - Microsoft Visual Studio Community 2015
10/13/2015 4:20:20 PM - The extension will be upgraded from version 1.0.12.1.
10/13/2015 4:20:20 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
10/13/2015 4:20:20 PM - Found installed product - Global Location
10/13/2015 4:20:23 PM - The following target products have been selected...
10/13/2015 4:20:23 PM - 	Microsoft Visual Studio Community 2015
10/13/2015 4:20:23 PM - 
10/13/2015 4:20:24 PM - Beginning to install extension to Microsoft Visual Studio Community 2015...
10/13/2015 4:20:24 PM - Upgrading 'GitHub Extension for Visual Studio', version 1.0.12.1 to version 1.0.15.2.
10/13/2015 4:20:30 PM - Install Error : System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.AtomicallyDeleteFiles(IEnumerable`1 filePaths, Boolean justMarkForDeletion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.DeleteDiscoverableFiles(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.UninstallInternal(IInstalledExtension extension, Boolean forceDelete)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
```

**Comment by shana** [comment]
@DrYSG Perhaps your installation got into a bad state somehow, this upgrade log doesn't look good. What happens when you uninstall the extension via Tools / Extensions and Updates?

**Comment by DrYSG** [comment]
I hit the uninstall. I prompts for the admin username/password. A progress bar shows for about 5 seconds. it finishes. I close Tools/extensions. But it is still there next time I start VS2015. Any way do to a complete removal?

**Comment by shana** [comment]
@DrYSG Sounds like VS is stuck and can't install and uninstall things. Follow these instructions to remove the GitHub extension (and please be careful in following the instructions):

- Close VS and open `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions` in Explorer.
- You'll see a bunch of directories with random names. One of these directories is the GitHub extension. You can identify the correct directory by searching for the `GitHub.VisualStudio.dll` file. It will also have other `GitHub.*.dll` files inside.
- Once you've located the correct directory (and **double-checked that it is the correct directory**), delete it
- Open a visual studio 2015 command prompt and run `devenv /updateConfiguration`
- Open VS. The extension should no longer be installed.

**Comment by shana** [comment]
@prasethu From the log, looks like the VS extension manager failed to update the extension properly due to locked files. That might explain how it got so messed up.

**Comment by DrYSG** [comment]
It looks like it is replicated in 5 spererate folders. Should I kill all those folders?


![croppercapture 1](https://cloud.githubusercontent.com/assets/2865368/10468391/ce33b014-71cc-11e5-9674-a5831b4ef71b.jpg)

**Comment by shana** [comment]
@DrYSG Looks like your VS installation is definitely having problems there, there should be only one copy. Yes, kill all those folders.

**Comment by DrYSG** [comment]
new install worked after deleting all the old ones

```
10/13/2015 5:50:14 PM - Microsoft VSIX Installer
10/13/2015 5:50:14 PM - -------------------------------------------
10/13/2015 5:50:14 PM - Initializing Install...
10/13/2015 5:50:14 PM - Extension Details...
10/13/2015 5:50:14 PM - 	Identifier      : c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
10/13/2015 5:50:14 PM - 	Name            : GitHub Extension for Visual Studio
10/13/2015 5:50:14 PM - 	Author          : GitHub, Inc
10/13/2015 5:50:14 PM - 	Version         : 1.0.15.2
10/13/2015 5:50:14 PM - 	Description     : A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
10/13/2015 5:50:14 PM - 	Locale          : en-US
10/13/2015 5:50:14 PM - 	MoreInfoURL     : https://visualstudio.github.com/
10/13/2015 5:50:14 PM - 	InstalledByMSI  : False
10/13/2015 5:50:14 PM - 	SupportedFrameworkVersionRange : [4.5,)
10/13/2015 5:50:14 PM - 
10/13/2015 5:50:15 PM - 	SignedBy        : GitHub, Inc
10/13/2015 5:50:15 PM - 	Certificate Info : [Subject]
  CN="GitHub, Inc", OU=Digital ID Class 3 - Microsoft Software Validation v2, O="GitHub, Inc", L=San Francisco, S=California, C=US

[Issuer]
  CN=VeriSign Class 3 Code Signing 2010 CA, OU=Terms of use at https://www.verisign.com/rpa (c)10, OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US

[Serial Number]
  2EA078CF4DAE81459313B225E26B568B

[Not Before]
  3/7/2013 7:00:00 PM

[Not After]
  6/6/2016 7:59:59 PM

[Thumbprint]
  C5C87FB961A2318109A5A87561C9E90923685ED6

10/13/2015 5:50:15 PM - 	Supported Products : 
10/13/2015 5:50:15 PM - 		Microsoft.VisualStudio.Community
10/13/2015 5:50:15 PM - 			Version : [14.0,)
10/13/2015 5:50:15 PM - 
10/13/2015 5:50:15 PM - 	References      : 
10/13/2015 5:50:15 PM - 		-------------------------------------------------------
10/13/2015 5:50:15 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
10/13/2015 5:50:15 PM - 		Name         : Visual Studio MPF 14.0
10/13/2015 5:50:15 PM - 		Version      : [14.0]
10/13/2015 5:50:15 PM - 		MoreInfoURL  : 
10/13/2015 5:50:15 PM - 		Nested       : No
10/13/2015 5:50:15 PM - 
10/13/2015 5:50:15 PM - 
10/13/2015 5:50:15 PM - Searching for applicable products...
10/13/2015 5:50:15 PM - Found installed product - Microsoft Visual Studio Professional 2013
10/13/2015 5:50:15 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
10/13/2015 5:50:15 PM - Found installed product - Microsoft Visual Studio Community 2015
10/13/2015 5:50:18 PM - The extension with ID 'c3d3dc68-c977-411f-b3e8-03b0dccf7dfc' is not installed to Microsoft Visual Studio Community 2015.
10/13/2015 5:50:18 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
10/13/2015 5:50:18 PM - Found installed product - Global Location
10/13/2015 5:50:21 PM - The following target products have been selected...
10/13/2015 5:50:21 PM - 	Microsoft Visual Studio Community 2015
10/13/2015 5:50:21 PM - 
10/13/2015 5:50:22 PM - Beginning to install extension to Microsoft Visual Studio Community 2015...
10/13/2015 5:50:23 PM - Install to Microsoft Visual Studio Community 2015 completed successfully. The extension has been installed to C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\W2HY10SH.XN2\
````

**Comment by DrYSG** [comment]
question, do you know how I would connect to our local git server?

https://flatbed.draper.com/git/had.git

**Comment by shana** [comment]
@DrYSG If you want to do git operations in VS with your local git server, the only thing you have to do is open a project that is in a local clone of a repository hosted on your local git server, and then you can push, pull, commit and see history and branches in VS. FYI, the GitHub extension only deals with repositories hosted on GitHub, and doesn't do git operations, so it's not involved in these steps.
