### ISSUE TITLE
Error and hang/crash when opening PR detail

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#1293]
When opening #1283, got the following error message and then VS hung. Logged exception below.

![image](https://user-images.githubusercontent.com/310137/32424854-c886180c-c263-11e7-989a-edcf75bf34e0.png)

```
2017-11-05 19:54:54.9714|ERROR|thread: 1|PullRequestDetailViewModel|Error loading PullRequestModel
LibGit2Sharp.NotFoundException: could not find 'docs/contributing/images/clone-dialog.png' to open: The system cannot find the path specified.

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_status_list_new(RepositoryHandle repo, GitStatusOptions options)
   at LibGit2Sharp.RepositoryStatus..ctor(Repository repo, StatusOptions options)
   at LibGit2Sharp.RepositoryExtensions.RetrieveStatus(IRepository repository)
   at GitHub.Services.PullRequestService.IsWorkingDirectoryClean(ILocalRepositoryModel repository) in C:\projects\visualstudio\src\GitHub.App\Services\PullRequestService.cs:line 91
   at GitHub.ViewModels.PullRequestDetailViewModel.<Load>d__100.MoveNext() in C:\projects\visualstudio\src\GitHub.App\ViewModels\PullRequestDetailViewModel.cs:line 439    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_status_list_new(RepositoryHandle repo, GitStatusOptions options)
   at LibGit2Sharp.RepositoryStatus..ctor(Repository repo, StatusOptions options)
   at LibGit2Sharp.RepositoryExtensions.RetrieveStatus(IRepository repository)
   at GitHub.Services.PullRequestService.IsWorkingDirectoryClean(ILocalRepositoryModel repository) in C:\projects\visualstudio\src\GitHub.App\Services\PullRequestService.cs:line 91
   at GitHub.ViewModels.PullRequestDetailViewModel.<Load>d__100.MoveNext() in C:\projects\visualstudio\src\GitHub.App\ViewModels\PullRequestDetailViewModel.cs:line 439
```

**Comment by grokys** [comment]
I think this should have been fixed by #1337. Just tested and I'm not seeing the error. Closing this out unless it crops up again.
