### ISSUE TITLE
GitHub section on Connect page fails to load after recent update

### ISSUE THREAD

**Issue by prasethu** [github/VisualStudio#130]
/cc: @shana , @Haacked 

Internally, we're seeing the below error in the GitHub section:

System.Exception: The component 'GitHub.VisualStudio.UI.Views.GitHubConnectContent' does not have a resource identified by the URI '/GitHub.VisualStudio;component/ui/views/githubconnectcontent.xaml'.
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at GitHub.VisualStudio.UI.Views.GitHubConnectContent.InitializeComponent() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\UI\Views\GitHubConnectContent.xaml:line 1
   at GitHub.VisualStudio.UI.Views.GitHubConnectContent..ctor() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\UI\Views\GitHubConnectContent.xaml.cs:line 18
   at GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection.OnPropertyChange(Object sender, PropertyChangedEventArgs e) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\TeamExplorer\Connect\GitHubConnectSection.cs:line 183
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at GitHub.Primitives.NotificationAwareObject.RaisePropertyChanged(String propertyName) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.Exports\Helpers\NotificationAwareObject.cs:line 11
   at GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection.<Refresh>b__0(Object s, PropertyChangedEventArgs p) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\TeamExplorer\Connect\GitHubConnectSection.cs:line 134
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.RaisePropertyChanged(String propertyName)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.ViewModel_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Microsoft.TeamFoundation.MVVM.NotifyPropertyChangedDispatcherObject.RaisePropertyChanged(String propertyName)
   at Microsoft.TeamFoundation.MVVM.ViewModelBase.RaisePropertyChanged(String propertyName)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionViewModelBase.set_IsVisible(Boolean value)
   at Microsoft.VisualStudio.TeamFoundation.TeamExplorer.ConnectPage.InvitationSectionViewModel.UpdateVisibility()
   at Microsoft.VisualStudio.TeamFoundation.TeamExplorer.ConnectPage.InvitationSectionViewModel.set_PageViewModel(ConnectPageViewModel value)
   at Microsoft.VisualStudio.TeamFoundation.TeamExplorer.ConnectPage.InvitationSectionViewModel.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.InitializeViewModel(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

**Comment by prasethu** [comment]
![githubbug](https://cloud.githubusercontent.com/assets/9871368/10466818/1323edfa-71ab-11e5-8ab7-9575ea6fd6e0.png)

**Comment by shana** [comment]
This is really weird. What version of VS is this?

**Comment by prasethu** [comment]
The version of the extension is 1.0.15.2
I believe it is RTM, but I can double check.

**Comment by shana** [comment]
I'm looking at the dll in ILSpy (just to be sure nothing got screwed up in the packaging) and the xaml files are right there in the resources. I can only imagine that it's somehow loading the wrong files or not locating them? This is really odd.

**Comment by shana** [comment]
Can you try `devenv /updateConfiguration` and then run VS again?

**Comment by shana** [comment]
@prasethu So the other bug report like this was a result of previous installations of the extension not being removed when updated, and when an update failed, it became very confused about what it was loading. How many copies of the extension do you have on your system?

**Comment by prasethu** [comment]
this bug no longer repros after restart. Your theory about a resource being locked could be the issue, so I'm going to close it for now.
