### ISSUE TITLE
"could not find [file] to open" exception thrown when opening a PR

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#1326]
Got the following exception when trying to open PR #1292 

```
2017-11-17 13:34:37.5662|ERROR|thread: 1|PullRequestDetailViewModel|Error loading PullRequestModel
LibGit2Sharp.NotFoundException: could not find 'nuget.config' to open: The system cannot find the file specified.

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_status_list_new(RepositoryHandle repo, GitStatusOptions options)
   at LibGit2Sharp.RepositoryStatus..ctor(Repository repo, StatusOptions options)
   at LibGit2Sharp.RepositoryExtensions.RetrieveStatus(IRepository repository)
   at GitHub.Services.PullRequestService.IsWorkingDirectoryClean(ILocalRepositoryModel repository) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Services\PullRequestService.cs:line 91
   at GitHub.ViewModels.PullRequestDetailViewModel.<Load>d__100.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\ViewModels\PullRequestDetailViewModel.cs:line 439    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_status_list_new(RepositoryHandle repo, GitStatusOptions options)
   at LibGit2Sharp.RepositoryStatus..ctor(Repository repo, StatusOptions options)
   at LibGit2Sharp.RepositoryExtensions.RetrieveStatus(IRepository repository)
   at GitHub.Services.PullRequestService.IsWorkingDirectoryClean(ILocalRepositoryModel repository) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\Services\PullRequestService.cs:line 91
   at GitHub.ViewModels.PullRequestDetailViewModel.<Load>d__100.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.App\ViewModels\PullRequestDetailViewModel.cs:line 439
```

**Comment by shana** [comment]
This should be fixed by #1316 and #1321 (for the 2.3.4 tree)
