### ISSUE TITLE
Visual Studio 2015 Update 1 RC errors

### ISSUE THREAD

**Issue by xperiandri** [github/VisualStudio#142]
"Plug" page
```
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection0". ---> System.Exception: The component 'GitHub.VisualStudio.UI.Views.GitHubConnectContent' does not have a resource identified by the URI '/GitHub.VisualStudio;component/ui/views/githubconnectcontent.xaml'.
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at GitHub.VisualStudio.UI.Views.GitHubConnectContent.InitializeComponent() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\UI\Views\GitHubConnectContent.xaml:line 1
   at GitHub.VisualStudio.UI.Views.GitHubConnectContent..ctor() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\UI\Views\GitHubConnectContent.xaml.cs:line 18
   at GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection.OnPropertyChange(Object sender, PropertyChangedEventArgs e) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\TeamExplorer\Connect\GitHubConnectSection.cs:line 183
   at GitHub.Primitives.NotificationAwareObject.RaisePropertyChanged(String propertyName) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.Exports\Helpers\NotificationAwareObject.cs:line 11
   at GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection.Refresh(IConnection connection) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\TeamExplorer\Connect\GitHubConnectSection.cs:line 148
   at GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection.UpdateConnection() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\TeamExplorer\Connect\GitHubConnectSection.cs:line 175
   at GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection..ctor(ISimpleApiClientFactory apiFactory, ITeamExplorerServiceHolder holder, IConnectionManager manager, Int32 index) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\TeamExplorer\Connect\GitHubConnectSection.cs:line 97
   at GitHub.VisualStudio.TeamExplorer.Connect.GitHubConnectSection0..ctor(ISimpleApiClientFactory apiFactory, ITeamExplorerServiceHolder holder, IConnectionManager manager) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\TeamExplorer\Connect\GitHubConnectSection0.cs:line 17
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass6_0`2.<CreateStronglyTypedExportFactoryOfTM>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```

Project page
```
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection". ---> System.Exception: The component 'GitHub.VisualStudio.UI.Views.GitHubHomeContent' does not have a resource identified by the URI '/GitHub.VisualStudio;component/ui/views/githubhomecontent.xaml'.
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at GitHub.VisualStudio.UI.Views.GitHubHomeContent.InitializeComponent() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\UI\Views\GitHubHomeContent.xaml:line 1
   at GitHub.VisualStudio.UI.Views.GitHubHomeContent..ctor() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\UI\Views\GitHubHomeContent.xaml.cs:line 15
   at GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection..ctor(ISimpleApiClientFactory apiFactory, ITeamExplorerServiceHolder holder) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\TeamExplorer\Home\GitHubHomeSection.cs:line 27
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass6_0`2.<CreateStronglyTypedExportFactoryOfTM>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```

**Comment by xperiandri** [comment]
Visual Studio 2015 Enterprise with Update 1 RC clean installation.
I men that I uninstalled Visual Studio 2015 before because performing its update with Update 1 RC only was unsuccessful.

**Comment by xperiandri** [comment]
Next time I loaded Visual Studio this stack trace did not appear instead of GitHub Extension UI

**Comment by shana** [comment]
We've seen this before. Sometimes it seems VS gets confused about which dlls to load, and ends up unable to load the extension. Sometimes the extension update process doesn't uninstall the previous version and it gets confused. Is it still happening?

**Comment by prasethu** [comment]
@xperiandri Correct me if i'm wrong, but this was your scenario:
- You had VS 2015 RTM with the GitHub extension installed
- You uninstalled VS 2015 RTM
- You installed VS 2015 Update 1 RC slipstream install
- You launched VS and saw the error when you clicked the plug
- You restarted VS and the error went away.

**Comment by AlexEyler** [comment]
@xperiandri could you share with me the contents of your ComponentModelCache folder (%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache)? I'd like to investigate if this is a MEF issue on the VS side of things.

**Comment by AlexEyler** [comment]
@xperiandri could you also share any VSIXInstaller logs from %TEMP%? They should match this string: %TEMP%\VSIXInstaller_*.log. Hopefully you'll still have the VSIXInstaller log for the GitHub extension, and we can see if it ran into any issues uninstalling the previous version.

**Comment by xperiandri** [comment]
@prasethu, absolutely correct

**Comment by prasethu** [comment]
We're getting more and more feedback about this issue. While @AlexEyler looks at the VSIX logs, @shana Any updates on your side?

**Comment by shana** [comment]
@prasethu I really have no idea what's going on. People update VS and VS apparently doesn't clear the previous installation or something to that effect, so when it loads it fails to load the xaml resources that are a part of the DLL that throws the error (?!?). Both the class and the xaml file are in the same DLL, so why is it throwing saying it can't find the xaml resource?

Is Update 1 installer installing the extension from the vsix feed? Or is it still grabbing the old msi? That's the only thing that I can think of that might throw a wrench in things.

**Comment by prasethu** [comment]
@shana Most folks running into the issue upgrade from the Extensions and Updates dialog. So I don't think it's related to the vsix feed.

**Comment by shana** [comment]
@prasethu But are they installing the extension when they install Update 1, and then updating via the extensions and updates? If they're uninstalling RTM and then installing Update 1 and not installing the extension, how are they seeing the error? (I assume extensions are uninstalled when you uninstall VS?)

@xperiandri Did you install the GitHub Extension during the Update 1 installation? Or did you install it afterwards (or not at all)?

**Comment by prasethu** [comment]
@shana We have an inhouse repro:
1. Install v1.0.12-beta0 
2. Upgrade to latest 
3. Restart VS

**Comment by shana** [comment]
@prasethu Cool, I'll test this scenario. Can you check, when you update and then restart VS, how many copies of the extension are in the Extensions directory?

**Comment by prasethu** [comment]
@shana We're seeing 2 in the instance that has the issue.

**Comment by shana** [comment]
@prasethu So the update is not uninstalling the previous version until a second VS restart? Do the two copies remain, or does the old one eventually go away?

**Comment by prasethu** [comment]
the old one goes away as soon as you open a new instance

**Comment by shana** [comment]
@prasethu But the error happens when there's two instances, right?

**Comment by prasethu** [comment]
@shana So soon after updating to the latest and restarting VS, the error is seen. If you attach to this instance and look at the modules, you will see 2 instances of the GitHub extension loaded. As soon as you open a new instance, the old version goes away and only the latest is loaded.

When we try to load the resource in question when both instances of the Extension are loaded, there is a check in LoadComponent which compares  bamlStream.Assembly != component.GetType().Assembly and throws the Exception (since the 2 assemblies are 2 different versions)

**Comment by shana** [comment]
@prasethu So I'm not sure what I can do :cry: The questions coming to mind right now are: Why is VS loading two copies of the extension? Why is it not uninstalling the previous version until a second restart?  

Does this only happen when upgrading VS, or does it also happen when installing new versions of the extension in an existing VS installation?

**Comment by prasethu** [comment]
I don't think there is much you can do on the extension side. We're investigating on our side.

**Comment by shana** [comment]
@prasethu Sorry I can't help more, it's really annoying. We've only gotten a couple of reports about this (this one and one other iirc), so either people are not jumping into Update 1 (likely) or this only happens in some instances (Windows 10 perhaps? the vsix installer is really having problems there). Let me know if I can help out with anything.

**Comment by xperiandri** [comment]
As it is RC we can wait for RTM which have to come soon

**Comment by xperiandri** [comment]
> Did you install the GitHub Extension during the Update 1 installation? Or did you install it afterwards (or not at all)?
I installed it during VS2015 Enterprise with Update 1 RC installation. And that stack trace in Team Explorer appeared after I first time launched VS.

**Comment by shana** [comment]
Can't do much about this on our side, closing.

**Comment by xperiandri** [comment]
Agree
Moreover it is not relevant because of Update 1 RTM
