### ISSUE TITLE
Compare with Unmodified VS2017 stopped running

### ISSUE THREAD

**Issue by sebascomeau** [github/VisualStudio#1454]
- GitHub Extension for Visual Studio  version: 2.4.0.1202
- Visual Studio version: 15.5.5

I updated to the latest version and each time I try to do "Compare with Unmodified..." on a file that has changed then VS2017 hang and stop running.

I did a revert to version 2.2.0.10 and everything is fine now.

**Comment by shana** [comment]
@sebascomeau Could you try installing the previous version, v2.3.6.391, and see if it works for you?
 You can download the vsix from https://ghfvs-installer.github.com/releases/2.3.6.391/GitHub.VisualStudio.vsix and double click it to install it.

**Comment by grokys** [comment]
Hi @sebascomeau,

Thanks for letting us know - that is strange as the "Compare with Unmodified..." feature is a part of Visual Studio Team Explorer and not our extension...

I've just tried it locally and didn't see a problem, so it looks like it's something to do with your local setup. If you get a chance to go back to a version that is crashing, I wonder if you'd be able to attach a debugger and get a stack trace of where the crash is occurring?

You can do this by running another instance of Visual Studio and choosing "Debug -> Attach to Process" then selecting `devenv.exe` from the list.

**Comment by grokys** [comment]
Another thing you could try is clearing the MEF cache. There are instuctions for that [here](https://github.com/github/VisualStudio/issues/1455#issuecomment-362638935).

**Comment by TylerBrinkley** [comment]
I'm experiencing the same.

**Comment by grokys** [comment]
Hi @TylerBrinkley. This looks like it's becoming a common issue. Could you try clearing the MEF cache as described [here](https://github.com/github/VisualStudio/issues/1455#issuecomment-362638935)?

**Comment by TylerBrinkley** [comment]
I already reverted.

**Comment by sebascomeau** [comment]
I removed it from VS2017 then reinstall it.
No more bug now.

**Comment by grokys** [comment]
Good to know @sebascomeau, thanks for getting back to us! I suspect that clearing the MEF cache would have the same effect, but whatever was easiest for you!

**Comment by jcansdale** [comment]
@TylerBrinkley,

Could you try installing the following version over your reverted install (download the .zip and open the .vsix file from inside it):
https://ci.appveyor.com/project/github-windows/visualstudio/build/2.4.1.1219/artifacts

It includes a workaround for this issue. Please let us know if this version works as expected!

**Comment by TylerBrinkley** [comment]
@jcansdale It's working for me

**Comment by jcansdale** [comment]
@TylerBrinkley thanks for the quick reply! Good to know this version is working. 👍

**Comment by gpshonik** [comment]
Confirming that clearing the MEF cache fixed the issue for me.

**Comment by dekipet** [comment]
@jcansdale 
I experienced the problem described and version 2.4.1.1219 resolved this.

**Comment by NotThatBen** [comment]
Removing ang reinstalling extension fix this issue for me.

**Comment by Jehoel** [comment]
FWIW, here's the stack-trace for the crash reported in the Event Log. It happens whenever I do a File Comparison in the Team Explorer Changes window.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at GitHub.VisualStudio.GitHubServiceProvider.GetService(System.Type)
   at GitHub.VisualStudio.GitHubServiceProvider.GetService[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at GitHub.VisualStudio.GitHubProviderDispatcher.GetService[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at GitHub.InlineReviews.InlineCommentMarginProvider.get_SessionManager()
   at GitHub.InlineReviews.InlineCommentMarginProvider.IsMarginVisible(Microsoft.VisualStudio.Text.ITextBuffer)
   at GitHub.InlineReviews.Glyph.GlyphMargin`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].RefreshMarginVisibility()
   at GitHub.InlineReviews.Glyph.GlyphMargin`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnLoaded(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by wmjordan** [comment]
I had the same issue and the stack trace in Windows Event log was the same as @Jehoel posted.

**Comment by wmjordan** [comment]
@jcansdale Build 1219 was working for me too.

**Comment by jcansdale** [comment]
@Jehoel Thanks very much for the stack trace. I was hoping to get one of these! 👍

**Comment by rafalowski** [comment]
@jcansdale  build 1219 fixed the issue 
thanks

**Comment by weitzhandler** [comment]
Same here.
1219 fixes issue.

**Comment by grokys** [comment]
Closing this as the version with the fix (2.4.1) was released Monday!

**Comment by Toemsel** [comment]
In my case: GhostDocs required an update.
