### ISSUE TITLE
Team Explorer and GitHub pane show the wrong repository

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#1493]
Steps to repro:

- Pin VS to the windows taskbar
- Open VS
- Open a solution in repository A
- Open a solution in repository B
- Close VS
- Right click on the VS icon in the taskbar and select solution in Repository A

Expected: GHfVS displays the information of Repository A in Team Explorer Home and GitHub pane 
Actual: GHfVS displays the information of Repository B in Team Explorer Home and GitHub pane 

This is likely a regression after 2.3.6.391

Screenshots of issue:
![image 1](https://user-images.githubusercontent.com/10103121/36273625-f01b3c8c-1239-11e8-9227-71fe4404faae.png)

![image](https://user-images.githubusercontent.com/10103121/36273618-ea56705a-1239-11e8-88a9-def2c30cdee8.png)

Gif of issue:
![switching-repos-bug](https://user-images.githubusercontent.com/10103121/36274271-03bd8482-123c-11e8-87ca-cfc780dcb200.gif)

**Comment by meaghanlewis** [comment]
Error from log file:

```2018-02-15 10:23:47.571 EROR [01] PullRequestSessionManager Error changing repository
Octokit.NotFoundException: Not Found
   at Octokit.Connection.HandleErrors(IResponse response) in C:\projects\visualstudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 607
   at Octokit.Connection.<RunRequest>d__55.MoveNext() in C:\projects\visualstudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 588
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__54`1.MoveNext() in C:\projects\visualstudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 573
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__8`1.MoveNext() in C:\projects\visualstudio\submodules\octokit.net\Octokit\Http\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception)
   at System.Reactive.Subjects.AsyncSubject`1.GetResult()
   at GitHub.InlineReviews.Services.PullRequestSessionManager.<StatusChanged>d__19.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 224
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#get-a-single-pull-request"}
2018-02-15 10:26:34.600 INFO [01] GitHubPackage             Initializing GitHub Extension v2.4.2.1331 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-02-15 10:26:58.338 EROR [01] PullRequestSessionManager Error changing repository
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at GitHub.InlineReviews.Services.PullRequestSessionManager.<StatusChanged>d__19.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews```

**Comment by grokys** [comment]
On https://github.com/github/VisualStudio/tree/fixes/1493-wrong-repo I added some logging. I then created two shortcuts to run the experimental instance: one to open `github/VisualStudio` and one to open `haacked/Rothko`.

Clicking on the first shortcut (`github/VisualStudio`) followed by the second `(`haacked/Rothko`) reproduced the bug. Here is the log produced:

```
2018-02-16 15:48:33.059 INFO [01] GitHubPackage             Initializing GitHub Extension v2.4.3.0 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-02-16 15:48:34.486 DBUG [01] VSGitExt                  ActiveRepositories changed to []
2018-02-16 15:48:34.488 DBUG [01] VSGitExt                  Found IGitExt service and initialized VSGitExt
2018-02-16 15:48:34.492 DBUG [17] VSGitExt                  IGitExt.ActiveRepositories (#43546682) returned ["C:\\Users\\grokys\\Source\\Repos\\VisualStudio"]
2018-02-16 15:48:34.965 DBUG [15] VSGitExt                  IGitExt.ActiveRepositories (#43546682) returned ["D:\\projects\\Rothko"]
2018-02-16 15:48:37.004 DBUG [15] VSGitExt                  ActiveRepositories changed to ["https://github.com/editor-tools/Rothko"]
2018-02-16 15:48:37.004 DBUG [17] VSGitExt                  ActiveRepositories changed to ["https://github.com/github/VisualStudio"]
2018-02-16 15:48:37.389 DBUG [15] TeamExplorerContext       ActiveRepository changed to https://github.com/editor-tools/Rothko @ D:\projects\Rothko
2018-02-16 15:48:37.391 DBUG [17] TeamExplorerContext       ActiveRepository changed to https://github.com/github/VisualStudio @ C:\Users\grokys\Source\Repos\VisualStudio
```

**Comment by shana** [comment]
Nice spelunking there, good work!
