### ISSUE TITLE
Flaky and failing tests

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#1722]
#### Test Explorer

- OrderByDoesntMatchOriginalOrderTimings
```
Test Name:	OrderByDoesntMatchOriginalOrderTimings
Test FullName:	TrackingTests.OrderByDoesntMatchOriginalOrderTimings
Test Source:	C:\Source\github.com\github\VisualStudio\test\TrackingCollectionTests\TrackingCollectionTests.cs : line 378
Test Outcome:	Failed
Test Duration:	0:00:00.388

Result StackTrace:	at TrackingTests.OrderByDoesntMatchOriginalOrderTimings() in C:\Source\github.com\github\VisualStudio\test\TrackingCollectionTests\TrackingCollectionTests.cs:line 419
Result Message:	
Expected: less than or equal to 200.0d
  But was:  239.99870000000001d
```

#### NCrunch

- LoadingResourceDictionaryIntegrationTests
- SharedDictionaryManagerIntegrationTests

![image](https://user-images.githubusercontent.com/11719160/41170120-f5271842-6b42-11e8-9290-ea21994dac4b.png)

These appear to be failing because of exceptions like this:
```
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.TypeInitializationException : The type initializer for 'GitHub.LoadingResourceDictionary' threw an exception.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'Serilog.Enrichers.Process, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. The system cannot find the file specified.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
```
- `TrackingTests`

![image](https://user-images.githubusercontent.com/11719160/41170208-37790322-6b43-11e8-8999-74decc6c4275.png)

- Various

![image](https://user-images.githubusercontent.com/11719160/41170235-5670528a-6b43-11e8-93ba-0ceb6d8bb217.png)

#### AppVayer CI

- #1676: ActiveRepositoriesChangedOrderingShouldBeCorrectAcrossThreads

**Comment by grokys** [comment]
`RepoChangedHandlesNullRepository` just hung on Azure Pipelines.
