### ISSUE TITLE
Unable to leave inline comment on some lines

### ISSUE THREAD

**Issue by meaghanlewis** [github/VisualStudio#1731]
- GitHub Extension for Visual Studio version: VS2015/2017
- Visual Studio version: 2.5.3 master

## What happened

When trying to leaving an inline comment at various lines in this [file](https://github.com/github/VisualStudio/blob/43877a73c4f95bb8d4cb6bcf76dea45525307c32/src/GitHub.App/ViewModels/GitHubPane/PullRequestReviewCommentViewModel.cs#L64) there are errors.

**when starting a review:**
![validation failed](https://user-images.githubusercontent.com/10103121/41388575-6e61bef4-6f41-11e8-8cb0-75313e4a8f84.png)

**when adding a single comment:**
![position invalid](https://user-images.githubusercontent.com/10103121/41388587-80c994cc-6f41-11e8-9ae4-7c9a63333f3b.png)

snippet from logs:
```2018-06-13 19:30:07.893 [04524] EROR [01] CommentViewModel          Error posting comment
Octokit.ApiValidationException: Validation Failed
   at Octokit.Connection.HandleErrors(IResponse response) in C:\projects\visualstudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 652
   at Octokit.Connection.<RunRequest>d__57.MoveNext() in C:\projects\visualstudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 633
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__56`1.MoveNext() in C:\projects\visualstudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 618
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.PullRequestReviewCommentsClient.<Create>d__15.MoveNext() in C:\projects\visualstudio\submodules\octokit.net\Octokit\Clients\PullRequestReviewCommentsClient.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception)
   at System.Reactive.Subjects.AsyncSubject`1.GetResult()
   at GitHub.InlineReviews.Services.PullRequestSessionService.<PostStandaloneReviewComment>d__28.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionService.cs:line 542
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.Services.PullRequestSession.<PostReviewComment>d__19.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.ViewModels.NewInlineCommentThreadViewModel.<DoPostComment>d__18.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\ViewModels\NewInlineCommentThreadViewModel.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.ViewModels.CommentViewModel.<DoCommitEdit>d__15.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\ViewModels\CommentViewModel.cs:line 167
{"message":"Validation Failed","errors":[{"resource":"PullRequestReviewComment","code":"invalid","field":"position"}],"documentation_url":"https://developer.github.com/v3/pulls/comments/#create-a-comment"}
2018-06-13 19:30:16.152 [04524] EROR [01] CommentViewModel          Error posting comment
Octokit.GraphQL.Core.GraphQLQueryException: Position is invalid
   at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize[TResult](CompiledQuery`1 query, JObject data)
   at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize[TResult](CompiledQuery`1 query, String data)
   at Octokit.GraphQL.Connection.<Run>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GitHub.InlineReviews.Services.PullRequestSessionService.<PostPendingReviewComment>d__26.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionService.cs:line 481
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.Services.PullRequestSession.<PostReviewComment>d__19.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.ViewModels.NewInlineCommentThreadViewModel.<DoPostComment>d__18.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\ViewModels\NewInlineCommentThreadViewModel.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.ViewModels.CommentViewModel.<DoCommitEdit>d__15.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\ViewModels\CommentViewModel.cs:line 167
```

**Comment by meaghanlewis** [comment]
@jcansdale discovered this in: https://github.com/github/VisualStudio/pull/1712 but this issue is present on master as well.

**Comment by grokys** [comment]
I _suspect_ this is related to https://github.com/github/VisualStudio/issues/1469 though I'm yet to confirm that.

**Comment by Faithfulness22** [comment]
your trends on your website are so amazing and it is like i have never seen an article like yours before. keep doing your good works and i 
  <a href="https://www.tecteem.com/wapmight/">will always check on your website for updates.</a>
