### ISSUE TITLE
Getting error message: Specified argument was out of the range of valid values

### ISSUE THREAD

**Issue by virenv** [github/VisualStudio#1963]
## Version
VS version: Professional 2017, 15.8.2
Extension version: 2.5.5.3931

## What happened
When I added a comment to the PR, it gave me this error message. It does not come all the time but I can see it today like almost every alternate time I add a comment.
**Steps to Reproduce**

1. Open a PR
2. Try adding multiple comments, in one of the comments you should get the error message

**Expected behavior:** Comment should be added without any issue

**Actual behavior:** Getting error message: Specified argument was out of the range of valid values. ParameterName: lineNumbers
![2018-09-30](https://user-images.githubusercontent.com/6619269/46253101-2b445280-c491-11e8-9d2e-90c258afa1fb.png)

**Screenshot or GIF:**

**Comment by virenv** [comment]
Adding additional logs from the log file

2018-09-29 12:28:20.006 [05924] EROR [01] VSServices                GetServiceSafe: Could not obtain instance of 'Microsoft.TeamFoundation.Controls.ITeamExplorerPage'
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.Extensions.IServiceProviderExtensions.GetServiceSafe(IServiceProvider serviceProvider, Type type) in C:\projects\visualstudio\src\GitHub.Exports\Extensions\ServiceProviderExtensions.cs:line 36
2018-09-29 12:29:20.603 [05924] INFO [40] GitHubPackage             Initializing GitHub Extension v2.5.5.3913 in Microsoft Visual Studio 2017 (15.8.28010.2016)
2018-09-29 12:55:48.562 [26512] INFO [57] GitHubPackage             Initializing GitHub Extension v2.5.5.3913 in Microsoft Visual Studio 2017 (15.8.28010.2016)
2018-09-30 09:00:11.229 [05924] EROR [01] CommentViewModel          Error posting comment
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: lineNumber
   at Microsoft.VisualStudio.Text.Implementation.UnaryStringRebuilder.GetLineFromLineNumber(Int32 lineNumber, Span& extent, Int32& lineBreakLength)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.GetLineFromLineNumber(Int32 lineNumber)
   at GitHub.InlineReviews.Tags.InlineCommentTagger.NotifyTagsChanged(Int32 lineNumber) in C:\projects\visualstudio\src\GitHub.InlineReviews\Tags\InlineCommentTagger.cs:line 222
   at GitHub.InlineReviews.Tags.InlineCommentTagger.NotifyTagsChanged(IEnumerable`1 lineNumbers) in C:\projects\visualstudio\src\GitHub.InlineReviews\Tags\InlineCommentTagger.cs:line 231
   at GitHub.InlineReviews.Tags.InlineCommentTagger.LinesChanged(IReadOnlyList`1 lines) in C:\projects\visualstudio\src\GitHub.InlineReviews\Tags\InlineCommentTagger.cs:line 211
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.Observer`1.OnNext(T value)
   at GitHub.InlineReviews.Models.PullRequestSessionFile.set_InlineCommentThreads(IReadOnlyList`1 value) in C:\projects\visualstudio\src\GitHub.InlineReviews\Models\PullRequestSessionFile.cs:line 95
   at GitHub.InlineReviews.Services.PullRequestSession.<UpdateFile>d__25.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 312
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.Services.PullRequestSession.<Update>d__23.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 283
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.Services.PullRequestSession.<PostReviewComment>d__15.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.ViewModels.NewInlineCommentThreadViewModel.<DoPostComment>d__17.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\ViewModels\NewInlineCommentThreadViewModel.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.ViewModels.CommentViewModel.<DoCommitEdit>d__16.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\ViewModels\CommentViewModel.cs:line 194
2018-09-30 09:00:41.366 [05924] EROR [01] CommentViewModel          Error posting comment
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: lineNumber
   at Microsoft.VisualStudio.Text.Implementation.UnaryStringRebuilder.GetLineFromLineNumber(Int32 lineNumber, Span& extent, Int32& lineBreakLength)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.GetLineFromLineNumber(Int32 lineNumber)
   at GitHub.InlineReviews.Tags.InlineCommentTagger.NotifyTagsChanged(Int32 lineNumber) in C:\projects\visualstudio\src\GitHub.InlineReviews\Tags\InlineCommentTagger.cs:line 222
   at GitHub.InlineReviews.Tags.InlineCommentTagger.NotifyTagsChanged(IEnumerable`1 lineNumbers) in C:\projects\visualstudio\src\GitHub.InlineReviews\Tags\InlineCommentTagger.cs:line 231
   at GitHub.InlineReviews.Tags.InlineCommentTagger.LinesChanged(IReadOnlyList`1 lines) in C:\projects\visualstudio\src\GitHub.InlineReviews\Tags\InlineCommentTagger.cs:line 211
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.Observer`1.OnNext(T value)
   at GitHub.InlineReviews.Models.PullRequestSessionFile.set_InlineCommentThreads(IReadOnlyList`1 value) in C:\projects\visualstudio\src\GitHub.InlineReviews\Models\PullRequestSessionFile.cs:line 95
   at GitHub.InlineReviews.Services.PullRequestSession.<UpdateFile>d__25.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 312
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.Services.PullRequestSession.<Update>d__23.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 283
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.Services.PullRequestSession.<PostReviewComment>d__15.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.ViewModels.NewInlineCommentThreadViewModel.<DoPostComment>d__17.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\ViewModels\NewInlineCommentThreadViewModel.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.ViewModels.CommentViewModel.<DoCommitEdit>d__16.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\ViewModels\CommentViewModel.cs:line 194
2018-09-30 09:09:37.394 [05924] EROR [01] CommentViewModel          Error posting comment
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: lineNumber
   at Microsoft.VisualStudio.Text.Implementation.UnaryStringRebuilder.GetLineFromLineNumber(Int32 lineNumber, Span& extent, Int32& lineBreakLength)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.GetLineFromLineNumber(Int32 lineNumber)
   at GitHub.InlineReviews.Tags.InlineCommentTagger.NotifyTagsChanged(Int32 lineNumber) in C:\projects\visualstudio\src\GitHub.InlineReviews\Tags\InlineCommentTagger.cs:line 222
   at GitHub.InlineReviews.Tags.InlineCommentTagger.NotifyTagsChanged(IEnumerable`1 lineNumbers) in C:\projects\visualstudio\src\GitHub.InlineReviews\Tags\InlineCommentTagger.cs:line 231
   at GitHub.InlineReviews.Tags.InlineCommentTagger.LinesChanged(IReadOnlyList`1 lines) in C:\projects\visualstudio\src\GitHub.InlineReviews\Tags\InlineCommentTagger.cs:line 211
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.Observer`1.OnNext(T value)
   at GitHub.InlineReviews.Models.PullRequestSessionFile.set_InlineCommentThreads(IReadOnlyList`1 value) in C:\projects\visualstudio\src\GitHub.InlineReviews\Models\PullRequestSessionFile.cs:line 95
   at GitHub.InlineReviews.Services.PullRequestSession.<UpdateFile>d__25.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 312
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.Services.PullRequestSession.<Update>d__23.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 283
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.Services.PullRequestSession.<PostReviewComment>d__15.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSession.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.ViewModels.NewInlineCommentThreadViewModel.<DoPostComment>d__17.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\ViewModels\NewInlineCommentThreadViewModel.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.InlineReviews.ViewModels.CommentViewModel.<DoCommitEdit>d__16.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\ViewModels\CommentViewModel.cs:line 194

**Comment by grokys** [comment]
@virenv is the PR you were commenting on publicly available? If so could you send me a link to the PR and file you were trying to comment on?

**Comment by virenv** [comment]
@grokys I am sorry, the PR has been closed now.
