### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0'

### ISSUE THREAD

**Issue by efev0f0** [github/VisualStudio#1969]
Using 2.5.6.4958, when trying to clone a repo, this exception is thrown. Thanks!

2018-10-03 16:17:54.949 [10996] EROR [01] RepositorySelectViewModel Error reading repository list from GitHub.Primitives.HostAddress
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Octokit.GraphQL.Core.Builders.QueryBuilder.Build[TResult](IQueryableValue`1 query)
   at Octokit.GraphQL.QueryableValueExtensions.Compile[T](IQueryableValue`1 expression)
   at GitHub.Services.RepositoryCloneService.<ReadViewerRepositories>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.ViewModels.Dialog.Clone.RepositorySelectViewModel.<Activate>d__37.MoveNext()

**Comment by mylle** [comment]
Same problem when opening the 'GitHub' View to to a pull request.
Any solutions?
![image](https://user-images.githubusercontent.com/18067020/46476340-30363880-c7e8-11e8-9157-3d0b447ea634.png)

**Comment by mylle** [comment]
Do I need to update the extension? If yes, how?

**Comment by grokys** [comment]
@efev0f0 @mylle firstly, could you let me know which version of Visual Studio you're on?

Secondly, I've opened a PR that might fix this: https://github.com/github/VisualStudio/pull/1975

Could you give that a try? You can download the artifacts from https://ci.appveyor.com/project/github-windows/visualstudio/build/2.5.6.5015/artifacts - download `GitHub.VisualStudio.vsix` and run it.

**Comment by mylle** [comment]
Visual Studio 2015: Version 14.0.25431.01 Update 3
GitHub.VisualStudio: 2.5.6.4958

Update did not fix the problem

**Comment by grokys** [comment]
Yes, if you're on 2015 then that won't fix the problem - neither of you mentioned the version of VS you were using so I assumed 2017.

We're investigating 2015 now.

**Comment by grokys** [comment]
@mylle ok, hopefully we've got it this time: could you try the version here: https://ci.appveyor.com/project/github-windows/visualstudio/build/2.5.6.5020/artifacts

**Comment by jcansdale** [comment]
Thanks for reporting this.  The issue will be automatically cloned by #1975.

**Comment by mylle** [comment]
@grokys , this fixed my problem!
Thank you!
