### ISSUE TITLE
Fails to check out PR branch.

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#1986]
## Version

- GitHub Extension for Visual Studio version: 2.5.7.5090
- Visual Studio version: 15.8.7

## What happened

**Steps to Reproduce**

1. Clone https://github.com/AvaloniaUI/Avalonia
2. Open https://github.com/AvaloniaUI/Avalonia/pull/1952 in GitHub pane
3. Click "Checkout" link

**Expected behavior:** [What you expect to happen]

PR branch is checked out

**Actual behavior:** [What actually happens]

![image](https://user-images.githubusercontent.com/1775141/46765696-f8475d80-ccdf-11e8-9690-5d406fc02311.png)

**Log file:**

```
2018-10-10 22:53:41.150 [39972] EROR [06] GitClient                 Failed to fetch
LibGit2Sharp.LibGit2SharpException: Request failed with status code: 404
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions fetchOptions, String logMessage)
   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions options, String logMessage)
   at LibGit2Sharp.Network.Fetch(Remote remote, FetchOptions options)
   at GitHub.Services.GitClient.<>c__DisplayClass9_0.<Fetch>b__0()
```

**Comment by grokys** [comment]
I think this is caused by the fact that the fork that submitted the PR has a different name.
