### ISSUE TITLE
I keep getting "You are not logged into Github.." Messages on Sync.. every day / every machine

### ISSUE THREAD

**Issue by jbattermann** [github/VisualStudio#202]
So this seems a bit weird - after updating to the latest version of your VS Github extension it appears I am getting logged out.. every day.. on two different machines.

I have logged in again and again on both machines and these messages appear to come back every day..? I have 2-factor authentication enabled and therefore always hit that other bug where to 2fa dialog never closes for which I keep waiting a little while giving it some time and it appears to work by then (read: I seem to be logged in).. but having to do that over and over again every day is .. a bit.. annoying.

Is there any log / data the extension writes why this is happening & what might help you?

Cheers,
-Jörg

**Comment by shana** [comment]
@jbattermann That's definitely odd. Could you post the log that's in %LocalAppData%\GitHubVisualStudio\extension.log so I can see if there's clues?

Also, could you check the Windows Credential Manager to see if there are two entries there, one for git:github.com and another for https://github.com.

**Comment by jbattermann** [comment]
I've attached the (zipped) 
[extension.log.zip](https://github.com/github/VisualStudio/files/91080/extension.log.zip) file and yep, there are two entries in the credentials manager:

![capture](https://cloud.githubusercontent.com/assets/828/12339394/303f06c8-bb15-11e5-9890-5f7f9dbf4fec.PNG)

.. is that good or bad?

**Comment by shana** [comment]
@jbattermann That's good, that means you're logged in and git operations on github.com repositories will work inside VisualStudio (and anything else that knows to use your stored credentials)

The persistence looks wrong though! That's why you keep getting logged off every day, they're cleared when you log off. That's incredibly helpful, thank you! I'll get that fixed right away.

**Comment by jbattermann** [comment]
Woohoo - nice \o/ Thanks @shana

**Comment by shana** [comment]
@jbattermann I just published a beta with a fix for this. It's still undergoing testing, but if you want to try it out, you can download it from the releases page, or configure a gallery in Visual Studio to get beta versions.

To configure the beta gallery, go to `Tools / Options / Extensions and Updates` and add a new gallery with the url https://visualstudio.github.com/releases/feed.rss. You'll be able to access it in `Tools / Extensions and Updates` in the Online or Updates tab, and you'll be able to install the beta version (or older versions, if you want)

**Comment by jbattermann** [comment]
Thanks @shana for letting me know and getting this out so quickly - I've installed the beta, could log in (and the 2fa window DID close as its supposed to) AND I did stay logged in across Windows / session logouts and reboots - looks good to me :+1: !

**Comment by shana** [comment]
Awesome, thanks so much for the quick testing, glad to hear it's working!

**Comment by jbattermann** [comment]
Hrrrmmmm.. quick update here - I had to log in again today :-/ (on the machine I rebooted a few times yesterday and where it seemed to work perfectly fine) - the extension.log says the following:

```
2016-01-20 23:41:51.8291|WARN|thread: 1|RepositoryHost|Got an authorization exception
Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 564
   at Octokit.Connection.<RunRequest>d__51.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__50`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__7`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\ApiConnection.cs:line 0    at Octokit.Connection.HandleErrors(IResponse response) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 564
   at Octokit.Connection.<RunRequest>d__51.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__50`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__7`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\ApiConnection.cs:line 0
2016-01-20 23:41:51.9068|INFO|thread: 1|RepositoryHost|Log in from cache for login '(null)' to host 'https://api.github.com/' FAILED
2016-01-20 23:41:51.9224|WARN|thread: 1|RepositoryHost|Got an authorization exception
Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 564
   at Octokit.Connection.<RunRequest>d__51.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__50`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__7`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\ApiConnection.cs:line 0    at Octokit.Connection.HandleErrors(IResponse response) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 564
   at Octokit.Connection.<RunRequest>d__51.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__50`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__7`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\ApiConnection.cs:line 0
2016-01-20 23:41:51.9380|INFO|thread: 1|RepositoryHost|Log in from cache for login '(null)' to host 'https://api.github.com/' FAILED
2016-01-20 23:41:55.5465|WARN|thread: 1|RepositoryHost|Got an authorization exception
Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 564
   at Octokit.Connection.<RunRequest>d__51.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__50`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__7`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\ApiConnection.cs:line 0    at Octokit.Connection.HandleErrors(IResponse response) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 564
   at Octokit.Connection.<RunRequest>d__51.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 546
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__50`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 531
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__7`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\ApiConnection.cs:line 0
2016-01-20 23:41:55.5615|INFO|thread: 1|RepositoryHost|Log in from cache for login '(null)' to host 'https://api.github.com/' FAILED
2016-01-20 23:42:34.6475|INFO|thread: 1|RepositoryHost|Log in from cache for login 'jbattermann' to host 'https://api.github.com/' SUCCEEDED
2016-01-20 23:42:34.6516|INFO|thread: 1|RepositoryHosts|Log in to GitHub.com host 'https://api.github.com/' with username 'jb@joergbattermann.com' SUCCEEDED
```

I logged in again (2fa worked as expected again - window closing etc), I shutdown VS, and then rebooted the machine.. and I am still logged in.

Not sure what happened inbetween yesterday and tonight that cause the logout / error(s) above, but maybe you see something..

**Comment by shana** [comment]
Looks like it lost the credentials somehow? It shows null for the login... very odd. How do the credentials look like in the credential manager (those two entries you spotted before)? What is the persistence, Local Computer or Login Session?

**Comment by jbattermann** [comment]
Hrm - today it worked and I can't reproduce the problem from yesterday.. I'll just keep an eye on it and if it happens again, I'll just re-open this issue. Persistence is set to Local Computer in Windows' Credentials Manager - at least now it is.. I hadn't checked yesterday - however it says 'Modified 20.01.2016'.. so yesterday.

Ah well - I'll let you know if it re-occurs. Thanks a lot either way :)

**Comment by shana** [comment]
Thanks for the feedback! After you login today (or when you next login), let me know if the modified time for the credentials has changed. I would not expect that time to change, but if it is changing every day, that might point to a bug somewhere.

**Comment by jbattermann** [comment]
Nope - the modified date is still the 20th today.. and I didn't have to log in again.. so it looks good now.

Cheers,
-J
