### ISSUE TITLE
Visual Studio quits while changing branches

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#2061]
## Version

- GitHub Extension for Visual Studio version: 2.6.0 (dev)
- Visual Studio version: 2017

## What happened

Visual Studio exited when checking out a PR branch. This happened again when returning to the original PR branch.

**Steps to Reproduce**

1. Check out https://github.com/github/VisualStudio/pull/2060/commits/eed1e4e211143de5cb52f5ae0df20e002764ff1e
2.  Open #2056 in PR detail view
3. Click the `Checkout ...` link

**Expected behavior:**

The target PR branch is checked out.

**Actual behavior:**

Visual Studio quits and restarts.

**Log file:**

I found the following exceptions in the Windows `Event Viewer`.

![image](https://user-images.githubusercontent.com/11719160/48637663-4bd75600-e9c6-11e8-98a0-6e2dff28fa26.png)

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at EnvDTE.ProjectItem.get_FileNames(Int16)
   at StringResourceVisualizer.VSPackage+<HandleOpenSolution>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

```
Faulting application name: devenv.exe, version: 15.8.28010.2046, time stamp: 0x5bb6cee9
Faulting module name: KERNELBASE.dll, version: 10.0.17134.407, time stamp: 0xade8d4fe
Exception code: 0xe0434352
Fault offset: 0x00111812
Faulting process id: 0x58d8
Faulting application start time: 0x01d47dcff03b95df
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8e9ddd47-7bb7-4d0f-a2a7-0e36f571d63e
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at EnvDTE.ProjectItem.get_FileNames(Int16)
   at StringResourceVisualizer.VSPackage+<HandleOpenSolution>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by jcansdale** [comment]
It has just done this a 3rd time.  Before quitting is shows the following.

![image](https://user-images.githubusercontent.com/11719160/48637833-c30cea00-e9c6-11e8-81a2-e78adb9919c9.png)

**Comment by jcansdale** [comment]
I though we might be able to fix this issue by using the checkout functionality that comes with the built in version control. I've just tried checking out using the bottom right list of branches.

![image](https://user-images.githubusercontent.com/11719160/48638209-da98a280-e9c7-11e8-9677-377c1fea8a20.png)

It quit in exactly the same way. 😕

**Comment by jcansdale** [comment]
Thought the issue might be NCrunch looking at files as they're changed, but the issue also happens with NCrunch disabled.
