### ISSUE TITLE
Double clicking a folder in a pull request crashes Visual Studio

### ISSUE THREAD

**Issue by jeffpapp** [github/VisualStudio#2082]
## Versions
 - GitHub Extension for Visual Studio version: 2.5.10.5901
 - Visual Studio version: 15.9.2

## What happened

Every time I open a pull request in the GitHub pane of Visual Studio and double click a folder under the changes section it crashes Visual Studio.  

### Steps to Reproduce
1. Open the GitHub pane
2. Pick a Pull Request
3. Double click a folder
4. A spinning cursor shows up and then Visual Studio crashes and restarts

### Expected behavior

When I double click a folder I would expect it to either expand or collapse the folder contents.

### Logs

This error shows up in the event viewer after every crash.  I can also provide VS or extension logs if you want but they don't seems to have any useful information in them.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at GitHub.ViewModels.GitHubPane.PullRequestFilesViewModel+<>c__DisplayClass7_0.<.ctor>b__0(GitHub.ViewModels.GitHubPane.IPullRequestFileNode)
   at ReactiveUI.ReactiveCommand+<>c__DisplayClass12_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<CreateFromTask>b__0(System.__Canon)
   at ReactiveUI.ReactiveCommand`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Reactive.Unit, System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].Execute(System.__Canon)

Exception Info: ReactiveUI.UnhandledErrorException
   at ReactiveUI.RxApp+<>c__DisplayClass0_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(System.Reactive.Concurrency.IScheduler, System.Action)
   at System.Reactive.Concurrency.DispatcherScheduler+<>c__DisplayClass12_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by grokys** [comment]
Oh.. wow. Yes I can repro this! Really sorry about this, not sure when it started happening.

I'll start working on a fix ASAP!
