### ISSUE TITLE
Object Reference error when retrieving Pull Request

### ISSUE THREAD

**Issue by mvockerodt** [github/VisualStudio#2085]
Hi

I'm getting this now-and-then issue when trying to open a pull request (yesterday it was OK, today it isn't working at all): First I get this:

![image](https://user-images.githubusercontent.com/19954641/49066956-53e78f00-f22b-11e8-9026-6c80bfc63d10.png)

On refreshing it changes to:

![image](https://user-images.githubusercontent.com/19954641/49066967-59dd7000-f22b-11e8-8543-c6d591b5eee9.png)

This has been happening for a number of recent versions now already.

Here is the log (for two runs of VS). It is clear there are a number of errors being reported.

> 2018-11-27 09:45:51.352 [13764] INFO [47] GitHubPackage             Initializing GitHub Extension v2.5.10.5901 in Microsoft Visual Studio 2017 (15.9.28307.108)
> 2018-11-27 09:45:52.678 [13764] EROR [25] PullRequestSessionManager 
> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Octokit.GraphQL.Core.Deserializers.ResponseDeserializerException: Field 'baseRefOid' doesn't exist on type 'PullRequest'
>    --- End of inner exception stack trace ---
>    at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize(String data)
>    at Octokit.GraphQL.Core.PagedQuery`1.Runner.<RunPage>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Octokit.GraphQL.ConnectionExtensions.<Run>d__2`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionService.<ReadPullRequestDetail>d__23.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionService.cs:line 352
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<GetSessionInternal>d__18.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 242
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<StatusChanged>d__17.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 214
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<RepoChanged>d__16.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 193
>    --- End of inner exception stack trace ---
> ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Octokit.GraphQL.Core.Deserializers.ResponseDeserializerException: Field 'baseRefOid' doesn't exist on type 'PullRequest'
>    --- End of inner exception stack trace ---
>    at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize(String data)
>    at Octokit.GraphQL.Core.PagedQuery`1.Runner.<RunPage>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Octokit.GraphQL.ConnectionExtensions.<Run>d__2`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionService.<ReadPullRequestDetail>d__23.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionService.cs:line 352
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<GetSessionInternal>d__18.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 242
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<StatusChanged>d__17.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 214
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<RepoChanged>d__16.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 193
> ---> (Inner Exception #0) Octokit.GraphQL.Core.Deserializers.ResponseDeserializerException: Field 'baseRefOid' doesn't exist on type 'PullRequest'<---
> 
> ---> (Inner Exception #1) Octokit.GraphQL.Core.Deserializers.ResponseDeserializerException: Field 'headRefOid' doesn't exist on type 'PullRequest'<---
> <---
> 
> 2018-11-27 09:52:51.839 [12608] INFO [47] GitHubPackage             Initializing GitHub Extension v2.5.10.5901 in Microsoft Visual Studio 2017 (15.9.28307.108)
> 2018-11-27 09:52:52.926 [12608] EROR [21] PullRequestSessionManager 
> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Octokit.GraphQL.Core.Deserializers.ResponseDeserializerException: Field 'baseRefOid' doesn't exist on type 'PullRequest'
>    --- End of inner exception stack trace ---
>    at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize(String data)
>    at Octokit.GraphQL.Core.PagedQuery`1.Runner.<RunPage>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Octokit.GraphQL.ConnectionExtensions.<Run>d__2`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionService.<ReadPullRequestDetail>d__23.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionService.cs:line 352
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<GetSessionInternal>d__18.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 242
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<StatusChanged>d__17.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 214
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<RepoChanged>d__16.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 193
>    --- End of inner exception stack trace ---
> ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Octokit.GraphQL.Core.Deserializers.ResponseDeserializerException: Field 'baseRefOid' doesn't exist on type 'PullRequest'
>    --- End of inner exception stack trace ---
>    at Octokit.GraphQL.Core.Deserializers.ResponseDeserializer.Deserialize(String data)
>    at Octokit.GraphQL.Core.PagedQuery`1.Runner.<RunPage>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Octokit.GraphQL.ConnectionExtensions.<Run>d__2`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionService.<ReadPullRequestDetail>d__23.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionService.cs:line 352
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<GetSessionInternal>d__18.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 242
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<StatusChanged>d__17.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 214
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at GitHub.InlineReviews.Services.PullRequestSessionManager.<RepoChanged>d__16.MoveNext() in C:\projects\visualstudio\src\GitHub.InlineReviews\Services\PullRequestSessionManager.cs:line 193
> ---> (Inner Exception #0) Octokit.GraphQL.Core.Deserializers.ResponseDeserializerException: Field 'baseRefOid' doesn't exist on type 'PullRequest'<---
> 
> ---> (Inner Exception #1) Octokit.GraphQL.Core.Deserializers.ResponseDeserializerException: Field 'headRefOid' doesn't exist on type 'PullRequest'<---
> <---
> 
> 2018-11-27 09:54:33.097 [12608] EROR [01] PullRequestDetailViewModel Error loading pull request dev/scp-com/526 from github.llamasoft.com
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at GitHub.ViewModels.GitHubPane.PullRequestDetailViewModel.<Refresh>d__107.MoveNext() in C:\projects\visualstudio\src\GitHub.App\ViewModels\GitHubPane\PullRequestDetailViewModel.cs:line 0
>

**Comment by grokys** [comment]
Thanks for getting in touch @mvockerodt. Is this repository on github.com or on an enterprise instance?

**Comment by grokys** [comment]
Could you let me know which version your enterprise instance is on? I'm having difficulty understanding how this can be an intermittent problem because the error message is:

```
Field 'baseRefOid' doesn't exist on type 'PullRequest'
```

Which appears to be sent by the server in response to a GraphQL query. This field should either be present or not be present, I'm not quite sure how it can be present some times and others not! It could maybe be an enterprise bug?

**Comment by mvockerodt** [comment]
Perhaps a poor choice of words on my part, directed more to me trying new versions now and then to see if the issue is resolved before going back to an old one that does. You are correct and I would also expect it should always be happening. That said, let's identify why it is happening and the issue can hopefully be resolved either way.

The Help link on the context menu redirects me to https://help.github.com/enterprise/2.12/user, so I would expect 2.12 is the version.

**Comment by grokys** [comment]
Thanks for the info @mvockerodt: ok it looks like this is the problem. `baseRefOid` was only added to the enterprise GraphQL schema in [2.13](https://developer.github.com/enterprise/2.13/v4/object/pullrequest/). You can see it's not present in [2.12](https://developer.github.com/enterprise/2.12/v4/object/pullrequest/).

We do try to keep compatibility with enterprise versions less than a year old, but it seems in this case we accidentally took a dependency on GitHub Enterprise 2.13. However, it looks like 2.12 was originally released on 7 Dec 2017, so it's nearly at its end of life. Would you be able to update to 2.13 at any point soon? If this is vital for you we could look into trying to remove this dependency.

**Comment by mvockerodt** [comment]
Yea, I noticed the help page said it's eol on 12 December. I'll speak to our DevOps about considering an upgrade. Whether you can remove the dependency on your side easily is something only you can say. If it will not be practical then I would say at least I can work with an old version of the plugin for the moment.

**Comment by ryzngard** [comment]
I just hit this on the [dotnet/roslyn](https://github.com/dotnet/roslyn) repo. I don't know exactly how to get logs, but I'm happy to if someone can give me a link or location they are.

**Comment by meaghanlewis** [comment]
Another user reported experiencing this same error in Halp. Here's the log they provided:
```
2018-12-10 14:36:06.309 [03668] INFO [44] GitHubPackage             Initializing GitHub Extension v2.6.0.6187 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-12-10 15:26:30.747 [05892] INFO [18] GitHubPackage             Initializing GitHub Extension v2.6.0.6187 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-12-10 17:33:42.696 [05892] EROR [01] PullRequestDetailViewModel Error loading pull request Ipreo/isynd-sl/993 from code.ipreo.com
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.ViewModels.GitHubPane.PullRequestDetailViewModel.<Refresh>d__111.MoveNext() in C:\projects\visualstudio\src\GitHub.App\ViewModels\GitHubPane\PullRequestDetailViewModel.cs:line 0
2018-12-10 17:35:49.061 [04888] INFO [26] GitHubPackage             Initializing GitHub Extension v2.6.0.6187 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-12-10 17:46:25.855 [04888] EROR [01] PullRequestDetailViewModel Error loading pull request Ipreo/isynd-sl/994 from code.ipreo.com
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.ViewModels.GitHubPane.PullRequestDetailViewModel.<Refresh>d__111.MoveNext() in C:\projects\visualstudio\src\GitHub.App\ViewModels\GitHubPane\PullRequestDetailViewModel.cs:line 0
2018-12-10 18:44:35.316 [15812] INFO [37] GitHubPackage             Initializing GitHub Extension v2.6.0.6187 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-12-11 09:27:53.243 [02500] INFO [25] GitHubPackage             Initializing GitHub Extension v2.6.0.6187 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-12-11 16:44:42.620 [13640] INFO [26] GitHubPackage             Initializing GitHub Extension v2.6.0.6187 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-12-12 10:39:53.015 [12052] INFO [08] GitHubPackage             Initializing GitHub Extension v2.6.0.6187 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-12-12 13:01:12.678 [18224] INFO [06] GitHubPackage             Initializing GitHub Extension v2.6.0.6187 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-12-12 15:54:41.835 [05276] INFO [27] GitHubPackage             Initializing GitHub Extension v2.6.0.6187 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-12-12 16:26:03.952 [03344] INFO [41] GitHubPackage             Initializing GitHub Extension v2.6.0.6187 in Microsoft Visual Studio 2015 (14.0.25420.1)
2018-12-12 17:39:11.752 [03344] EROR [01] PullRequestDetailViewModel Error loading pull request Ipreo/isynd-sl/987 from code.ipreo.com
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.ViewModels.GitHubPane.PullRequestDetailViewModel.<Refresh>d__111.MoveNext() in C:\projects\visualstudio\src\GitHub.App\ViewModels\GitHubPane\PullRequestDetailViewModel.cs:line 0
2018-12-12 17:39:12.421 [03344] EROR [01] PullRequestDetailViewModel Error loading pull request Ipreo/isynd-sl/987 from code.ipreo.com
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.ViewModels.GitHubPane.PullRequestDetailViewModel.<Refresh>d__111.MoveNext() in C:\projects\visualstudio\src\GitHub.App\ViewModels\GitHubPane\PullRequestDetailViewModel.cs:line 0
2018-12-12 17:39:17.917 [03344] EROR [01] PullRequestDetailViewModel Error loading pull request Ipreo/isynd-sl/987 from code.ipreo.com
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.ViewModels.GitHubPane.PullRequestDetailViewModel.<Refresh>d__111.MoveNext() in C:\projects\visualstudio\src\GitHub.App\ViewModels\GitHubPane\PullRequestDetailViewModel.cs:line 0
```
