### ISSUE TITLE
Clone from VS 2019 Clone dialog doesnt work on First Launch

### ISSUE THREAD

**Issue by prasethu** [github/VisualStudio#2218]
Install the github extension with the changes related to cloning from Get To Code

Attempt to clone on the very first launch. 

Notice that the GitHub dialog dismisses and Get To Code remains visible and no repo is cloned.

**Comment by prasethu** [comment]
@jcansdale / @meaghanlewis 

//cc: @Jekelly

**Comment by jcansdale** [comment]
Damn, well this is a fun bug. 😉 

I think the issue is that when Visual Studio is launched for the very first time, no source control plug-in has been set. The current source control plug-in will automatically change to Git when a solution is opened from a Git repository.

We can repo this by changing the current source control plug-in to `None`:
![image](https://user-images.githubusercontent.com/11719160/52333202-8c0e0980-29f4-11e9-8efb-56fe6730fc1c.png)

Relaunch Visual Studio and attempt to clone a repository using `Clone or check out code > GitHub > Clone`. The following will appear in the log:

```
2019-02-06 09:47:47.720 [12532] EROR [01] RepositoryCloneService    Could not clone https://github.com/jcansdale/bin to C:\Source\github.com\jcansdale\bin
System.InvalidOperationException: Could not locate any instances of contract Microsoft.VisualStudio.TeamFoundation.Git.Extensibility.IGitActionsExt.
   at GitHub.VisualStudio.GitHubServiceProvider.GetService(Type serviceType) in C:\Source\github.com\github\VisualStudio\src\GitHub.VisualStudio\Services\GitHubServiceProvider.cs:line 147
   at GitHub.VisualStudio.GitHubServiceProvider.GetService[T]() in C:\Source\github.com\github\VisualStudio\src\GitHub.VisualStudio\Services\GitHubServiceProvider.cs:line 153
   at GitHub.Services.VSGitServices.<Clone>d__7.MoveNext() in C:\Source\github.com\github\VisualStudio\src\GitHub.TeamFoundation.14\Services\VSGitServices.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitHub.Services.RepositoryCloneService.<CloneRepository>d__14.MoveNext() in C:\Source\github.com\github\VisualStudio\src\GitHub.App\Services\RepositoryCloneService.cs:line 215
```

I'll start working on a fix.
