### ISSUE TITLE
Unable to login with Github login dialog in visual studio

### ISSUE THREAD

**Issue by poojarsn** [github/VisualStudio#2258]
## Versions
 - GitHub Extension for Visual Studio version: ...
 - Visual Studio version: ..2015.

### Steps to Reproduce
Unable to login to github. enter userid /pwd it says require authentication

### Logs
2019-03-05 12:21:53.068 [25716] EROR [01] LoginTabViewModel         Error logging into '"https://github.com/"' as 'xyz@something.com'
Octokit.AuthorizationException: Requires authentication
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.<RunRequest>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<GetUserAndCheckScopes>d__23.MoveNext() in C:\projects\visualstudio\src\GitHub.Api\LoginManager.cs:line 344
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<ReadUserWithRetry>d__22.MoveNext() in C:\projects\visualstudio\src\GitHub.Api\LoginManager.cs:line 333
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<LoginViaOAuth>d__14.MoveNext() in C:\projects\visualstudio\src\GitHub.Api\LoginManager.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.VisualStudio.ConnectionManager.<LogInViaOAuth>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.ViewModels.Dialog.LoginTabViewModel.<LoginToHostViaOAuth>d__56.MoveNext() in C:\projects\visualstudio\src\GitHub.App\ViewModels\Dialog\LoginTabViewModel.cs:line 173
{"message":"Requires authentication","documentation_url":"https://developer.github.com/v3/users/#get-the-authenticated-user"}

**Comment by hlsantos** [comment]
I'm having the same issue with GitHub and Visual Studio 2015, can not log in.
