### ISSUE TITLE
Sign in with browser doesn't re-activate Start Window on completion

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#2364]
## Versions
 - GitHub Extension for Visual Studio version: All
 - Visual Studio version: 2019

## What happened
1. Open Visual Studio 2019
2. Select `Clone or checkout code`
3. Select `GitHub` icon
4. Select `Sign in`
5. Select `GitHub` tab and `Sign in with your browser`
6. Web browser opened and sign in completed
7. Web browser remains on top (obscuring Start Window and Open from GitHub dialog)

### Expected behavior
After sign in completes Visual Studio should be re-activated and appear on top.

### Additional context
It appears the Main window is collapsed when the Start Window appears. I wasn't able to get the `Activate()` method to work (even calling it on the Start Window). It seems we need to find another way.

**Comment by jcansdale** [comment]
It looks like the current method we're using to bring to front (`Window.Activate()`) can cause the application to crash:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Window.VerifyHwndCreateShowState()
   at System.Windows.Window.Activate()
   at GitHub.VisualStudio.Views.Dialog.LoginCredentialsView+<>c.<.ctor>b__0_4(GitHub.Models.IConnection)
   at System.Reactive.AnonymousSafeObserver`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   at System.Reactive.Linq.ObservableImpl.Switch`1+_+InnerObserver[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   at System.Reactive.Linq.ObservableImpl.Merge`1+Observables+_+InnerObserver[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   at System.Reactive.SafeObserver`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   at System.Reactive.Linq.ObservableImpl.Select`2+Selector+_[[ReactiveUI.ReactiveCommand`2+ExecutionInfo[[System.Reactive.Unit, System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], ReactiveUI, Version=8.7.0.0, Culture=neutral, PublicKeyToken=31f8874b2ce7ed44],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(ExecutionInfo<System.Reactive.Unit,System.__Canon>)
   at System.Reactive.Linq.ObservableImpl.Where`1+Predicate+_[[ReactiveUI.ReactiveCommand`2+ExecutionInfo[[System.Reactive.Unit, System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], ReactiveUI, Version=8.7.0.0, Culture=neutral, PublicKeyToken=31f8874b2ce7ed44]].OnNext(ExecutionInfo<System.Reactive.Unit,System.__Canon>)
   at System.Reactive.SafeObserver`1[[ReactiveUI.ReactiveCommand`2+ExecutionInfo[[System.Reactive.Unit, System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], ReactiveUI, Version=8.7.0.0, Culture=neutral, PublicKeyToken=31f8874b2ce7ed44]].OnNext(ExecutionInfo<System.Reactive.Unit,System.__Canon>)
   at System.Reactive.ScheduledObserver`1[[ReactiveUI.ReactiveCommand`2+ExecutionInfo[[System.Reactive.Unit, System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], ReactiveUI, Version=8.7.0.0, Culture=neutral, PublicKeyToken=31f8874b2ce7ed44]].Run(System.Object, System.Action`1<System.Object>)
   at System.Reactive.Concurrency.Scheduler+<>c__DisplayClass49_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<InvokeRec1>b__0(System.__Canon)
   at System.Reactive.Concurrency.Scheduler.InvokeRec1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Reactive.Concurrency.IScheduler, Pair`2<System.__Canon,System.Action`2<System.__Canon,System.Action`1<System.__Canon>>>)
   at System.Reactive.Concurrency.DispatcherScheduler+<>c__DisplayClass12_0`1[[System.Reactive.Concurrency.Scheduler+Pair`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263]].<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

I'm not sure why it doesn't do this every time.
