### ISSUE TITLE
It doesn't work for visual studio professional 2019. Lower Version than required 

### ISSUE THREAD

**Issue by arlind-shkrela** [github/VisualStudio#2429]
## Versions
Visual studio professional 2019 

## What happened
I have two vs installed on my machine, it worked perfectly for vs professional 2017, and failed for 2019 
 
## Below you may found installation log 
```
10/16/2019 10:25:36 AM - Skipping 'C:\Program Files (x86)\Common Files\Microsoft\ExtensionManager\Extensions' as it doesn't exist
10/16/2019 10:25:36 AM - Skipping 'C:\Users\User\AppData\Local\Microsoft SDKs' as it doesn't exist
10/16/2019 10:25:36 AM - Beginning to install extension to Visual Studio Professional 2019...
10/16/2019 10:25:40 AM - Installation of GitHub.VisualStudio failed. The extension has a lower version than required by Visual Studio.  Please install the extension from Visual Studio Installer instead.
10/16/2019 10:25:40 AM - Install Error : System.InvalidOperationException: Installation of GitHub.VisualStudio failed. The extension has a lower version than required by Visual Studio.  Please install the extension from Visual Studio Installer instead.
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureComponentAndPackageAreHigherVersion(ILogger logger, IDependencyGraph dGraph, Catalog catalog, Component vsixComponent)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsixComponent, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
``` 

_NOTE: @jcansdale edited to include only pertinent part of the log._

**Comment by jcansdale** [comment]
@arlind-shkrela  thanks for letting me know!

Did you try to install using `Extensions > Manage Extensions`, or downloading the VSIX from the https://visualstudio.github.com/ website?

**Comment by arlind-shkrela** [comment]
Hi @jcansdale 
Yep throw extensions it worked fine 🥇 . I think that problem stays when downloading from the website. https://visualstudio.github.com/ .From log ...lower version. 
Thank you though

**Comment by jcansdale** [comment]
Same problem from the VS Marketplace now. 😭 

```
26/10/2019 05:27:59 - Install Error : System.InvalidOperationException: Installation of GitHub.VisualStudio failed. The extension has a lower version than required by Visual Studio.  Please install the extension from Visual Studio Installer instead.
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureComponentAndPackageAreHigherVersion(ILogger logger, IDependencyGraph dGraph, Catalog catalog, Component vsixComponent)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsixComponent, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

We need to publish a later version!

**Comment by jcansdale** [comment]
Fixed it:

```
26/10/2019 06:06:05 - Install to Microsoft Visual Studio Enterprise 2019 completed successfully. The extension has been installed to C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\EXTENSIONS\GITHUB\GITHUB\
```
