### ISSUE TITLE
unable to connect to GitHub using visual studio 2019

### ISSUE THREAD

**Issue by mohan023** [github/VisualStudio#2527]
Below is what I got in logs.

Octokit.AuthorizationException: Must authenticate to access this API.
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.<RunRequest>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Put>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<CreateAndDeleteExistingApplicationAuthorization>d__18.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.Api\LoginManager.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<Login>d__13.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.Api\LoginManager.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GitHub.Api.LoginManager.<Login>d__13.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.Api\LoginManager.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.VisualStudio.ConnectionManager.<LogIn>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.ViewModels.Dialog.LoginTabViewModel.<LogInToHost>d__55.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.App\ViewModels\Dialog\LoginTabViewModel.cs:line 159
{"message":"Must authenticate to access this API.","documentation_url":"https://developer.github.com/enterprise/2.19/v3"}

![image](https://user-images.githubusercontent.com/4489345/86252584-084c5280-bbd1-11ea-9dd9-07291b84dd4a.png)
![image](https://user-images.githubusercontent.com/4489345/86252662-1e5a1300-bbd1-11ea-9032-1f0ad4e094df.png)

**Comment by techduggu** [comment]
Note: Adding this comment here to provide more information (as already added into #2509 )

Hi Team,

Even I am facing this issue with GitHub extension with Visual Studio 2019. I have tried the above workarounds (uninstalling/reverting to previous version etc.) but no luck.

I am able to sign-in successfully to GitHub on my browser but through extension, when I click on 'Sign in with your browser' option, it opens the browser with the below URL and it just keeps loading:
https://github.com/login/oauth/authorize?client_id=a200baed193bb2088a6e&scope=user%2Crepo%2Cgist%2Cwrite%3Apublic_key%2Cread%3Aorg%2Cworkflow&state=cd3677b8-bf82-4d2d-80c2-71fb3ed7cb63

Below is the error captured from Github Extension log:

> 2020-08-15 22:29:05.832 [20420] INFO [58] GitHubPackage             Initializing GitHub Extension v2.11.104.25275 in Microsoft Visual Studio 2019 (16.6.30114.105)
2020-08-15 22:29:23.860 [20420] EROR [01] LoginTabViewModel         Error logging into '"https://github.com/"' as ''
Octokit.AuthorizationException: Requires authentication
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.<RunRequest>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<GetUserAndCheckScopes>d__23.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.Api\LoginManager.cs:line 346
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<ReadUserWithRetry>d__22.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.Api\LoginManager.cs:line 335
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<LoginViaOAuth>d__14.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.Api\LoginManager.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.VisualStudio.ConnectionManager.<LogInViaOAuth>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.ViewModels.Dialog.LoginTabViewModel.<LoginToHostViaOAuth>d__56.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.App\ViewModels\Dialog\LoginTabViewModel.cs:line 173
{"message":"Requires authentication","documentation_url":"https://docs.github.com/rest/reference/users#get-the-authenticated-user"}
2020-08-15 22:31:05.818 [20420] EROR [05] GitHubServiceProvider     Error loading GitHub.Services.IConnectionManager
System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)
   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)
   at GitHub.VisualStudio.GitHubServiceProvider.TryGetService(Type serviceType)
2020-08-15 22:34:32.192 [20420] EROR [01] LoginTabViewModel         Error logging into '"https://github.com/"' as ''
Octokit.AuthorizationException: Requires authentication
   at Octokit.Connection.HandleErrors(IResponse response)
   at Octokit.Connection.<RunRequest>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<GetUserAndCheckScopes>d__23.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.Api\LoginManager.cs:line 346
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<ReadUserWithRetry>d__22.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.Api\LoginManager.cs:line 335
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.Api.LoginManager.<LoginViaOAuth>d__14.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.Api\LoginManager.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.VisualStudio.ConnectionManager.<LogInViaOAuth>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitHub.ViewModels.Dialog.LoginTabViewModel.<LoginToHostViaOAuth>d__56.MoveNext() in D:\a\VisualStudio\VisualStudio\src\GitHub.App\ViewModels\Dialog\LoginTabViewModel.cs:line 173
{"message":"Requires authentication","documentation_url":"https://docs.github.com/rest/reference/users#get-the-authenticated-user"}

**Comment by cyounes** [comment]
I have the same problem, 

Logs here 
[extension.log](https://github.com/github/VisualStudio/files/5179537/extension.log)

**Comment by jcansdale** [comment]
@mohan023 @techduggu,

@cyounes was able to resolve this by opening Visual Studio as Administrator before logging in, see https://github.com/github/VisualStudio/issues/2550#issuecomment-703280956

Any chance you could give this a try?

**Comment by mohan023** [comment]
I'm still facing this issue. Tried most of the suggestions mentioned here.

**Comment by jcansdale** [comment]
@mohan023, I'm sorry this didn't fix it. Thanks for trying!

**Comment by jcansdale** [comment]
Hi @mohan023 (and @techduggu),

I think the issue you've been seeing might be this #2560 (reported by @osmanager). I've opened a PR that I hope will resolve the problem here #2562.

Could you try installing the artifact from this build:
https://github.com/github/VisualStudio/pull/2562/checks?check_run_id=1309274757

You can find it here:
https://github.com/github/VisualStudio/suites/1400504505/artifacts/23266202

After opening and installing the VSIX, can you let me know if it works any better? Any help confirming this fix would be much appreciated!

**Comment by BHinrichs1966** [comment]
@jcansdale  I have the same issue as Mohan023 and techduggu.  I tried using the link you provided,
https://github.com/github/VisualStudio/suites/1400504505/artifacts/23266202
but I receive a 404 error.

**Comment by jcansdale** [comment]
Hi @BHinrichs1966,

Could you try installing the artifact from this link?
https://github.com/github/VisualStudio/runs/1343191255?check_suite_focus=true

**Comment by BHinrichs1966** [comment]
I downloaded the new extension.  When I attempt to install it, it fails.

[cid:image001.png@01D6B1C7.46C8C7A0]

I am attaching the .log

I am able to install the “production” version of this extension using the VS extension manager.  But, not able to install this local copy.  My company does have restrictions on our machines.  I am not an administrator on my own machine.  Could that be causing this to fail?

Brad Hinrichs
Data Architect, Advisory
Bank Solutions
Office: 402-423-2682 x. 3966

Fiserv
Register Today! | Forum 2020 Virtual Experience<https://www.fiserv.com/en/forum-2020.html?utm_medium=link&utm_campaign=forum2020&utm_source=fiservsignature&utm_content=text_save_the_date>
Fiserv<https://www.fiserv.com/index.aspx> | Join Our Team<https://www.careers.fiserv.com/?utm_source=outlook&utm_medium=email&utm_campaign=signature> | Twitter<https://twitter.com/fiserv> | LinkedIn<https://www.linkedin.com/company/fiserv/> | Facebook<https://www.facebook.com/Fiserv/>
FORTUNE Magazine World's Most Admired Companies® 2014 | 2015 | 2016 | 2017 | 2018 | 2019 | 2020
© 2019 Fiserv, Inc. or its affiliates. Fiserv is a registered trademark of Fiserv, Inc. Privacy Policy<http://fiserv.com/about/privacypolicy.aspx>

**Comment by jcansdale** [comment]
@BHinrichs1966,

> I am able to install the “production” version of this extension using the VS extension manager.  But, not able to install this local copy.  My company does have restrictions on our machines.  I am not an administrator on my own machine.  Could that be causing this to fail?

Yes, that could be causing this to fail. I'll let you know when this fix has been confirmed and a new version has been pushed to production!

**Comment by mohan023** [comment]
Do we have anyone whose is not facing this issue anymore?

**Comment by ttaylor29** [comment]
@mohan023 I'm seeing this again :/

**Comment by jcansdale** [comment]
@mohan023, @ttaylor29,

Any chance you could try the VSIX artifact from this build?
https://github.com/github/VisualStudio/pull/2562/checks?check_run_id=1343191255

**Comment by ttaylor29** [comment]
@jcansdale Will this work if I just want normal GitHub and not the GitHub Enterprise Server?

**Comment by jcansdale** [comment]
@ttaylor29,

If there is an HTTP proxy between you and GitHub, it could make a difference. I'm interested to find out!

**Comment by ttaylor29** [comment]
@jcansdale I'll try this in a bit at lunch if I can!

**Comment by ttaylor29** [comment]
@jcansdale How do I implement this?

Any chance you could try the VSIX artifact from this build?
https://github.com/github/VisualStudio/pull/2562/checks?check_run_id=1343191255

FYI, I just tried it again with Chrome and it fails ; FireFox still works on my work laptop.

**Comment by ttaylor29** [comment]
> @jcansdale How do I implement this?
> 
> Any chance you could try the VSIX artifact from this build?
> https://github.com/github/VisualStudio/pull/2562/checks?check_run_id=1343191255
> 
> FYI, I just tried it again with Chrome and it fails ; FireFox still works on my work laptop.

Never mind, I found the artifact folder with the GitHub.VisualStudio.vsix

**Comment by ttaylor29** [comment]
@jcansdale It still failed :-(

- I go to sign in via this:

![image](https://user-images.githubusercontent.com/23564255/99611995-56c08900-29da-11eb-9a37-2fba41076004.png)

- Then I get this to show up

![image](https://user-images.githubusercontent.com/23564255/99612075-8374a080-29da-11eb-93b5-744f873cee21.png)

Then this shows up:

![image](https://user-images.githubusercontent.com/23564255/99611969-414b5f00-29da-11eb-9b89-f75d4890682c.png)

**Comment by ttaylor29** [comment]
@jcansdale 

I might have found it.

put this into Chrome address bar: 

**chrome://net-internals/#hsts**

Then go to the bottom and delete localhost from the **Delete domain security policies**

Then try to sign into GitHub via VS2019 and it worked!!!

Chrome and Edge are chromium underneath the hood, so that is why it is happening on both!

I think my work puts these settings on from the group policy. I have to do this with using IIS local to run my web application sometimes. 

![image](https://user-images.githubusercontent.com/23564255/99612526-5e346200-29db-11eb-9f46-a67e42127f91.png)

**Comment by jcansdale** [comment]
@ttaylor29 I'm glad you figured it out!

I wonder if it treats `localhost` the same as `127.0.0.1`? 🤔

**Comment by WagaoPRC** [comment]
> chrome://net-internals/#hsts

This method work for me. 
i have no problem with webapp then using localhost too. Maybe beacause adress is set for VS.

**Comment by mightysabean** [comment]
still having thesame issue.. tried all the suggestions, but no luck

**Comment by mightysabean** [comment]
What worked for me was deleting all my cookies and browsing history (From Microsoft Edge Browser)

**Comment by huytruongtdh** [comment]
> @jcansdale @mohan023
> 
> I might have found it.
> 
> put this into Chrome address bar:
> 
> **chrome://net-internals/#hsts**

This works for me. Thanks
