### ISSUE TITLE
VS 2019 Cannot log into GitHub

### ISSUE THREAD

**Issue by ttaylor29** [github/VisualStudio#2566]
Microsoft Visual Studio Professional 2019
Version 16.8.1

I cannot log into github via VS2019 Professional. 

I've had this issue before: https://github.com/github/VisualStudio/issues/2509

Nothing that I posted or anyone else posted has worked.

I start here after I log out of github.com with my default browser

![image](https://user-images.githubusercontent.com/23564255/99490135-e27cdb80-292e-11eb-8fed-c78fa16350dc.png)

Then I see this screen:

![image](https://user-images.githubusercontent.com/23564255/99490259-1d7f0f00-292f-11eb-9eab-c2458f837b07.png)

I log in with my proper credentials and it redirects me to this:

https://localhost:42549/?browser_session_id=555e66a9ec8daa42eea03b1037941114f832ccc9b294bc6a1d60c3a602df3dac&code=206fb75efb523c318ab9&state=7724d9a4-7594-4123-9ee8-80c4bf6b0f82

I've started VS with admin rights, I've deleted all of my personal tokens, rebooted, uninstalled the local extension, logged in via the VS direct way instead of the extension, EVERYTHING!

So right now, I can't use my github repos! 

Error in extension: C:\Users\username\AppData\Local\GitHubVisualStudio

2020-11-17 23:36:07.419 [16836] EROR [44] GitHubServiceProvider     Error loading GitHub.Services.IConnectionManager
System.InvalidOperationException: Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(Type serviceType)
   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(Type serviceType)
   at GitHub.VisualStudio.GitHubServiceProvider.TryGetService(Type serviceType)

So it is what I saw from the previous issue in May, but nothing will work now!

Please help!

**Comment by ttaylor29** [comment]
I changed my default browser to **FireFox** and everything started working and it would let me sign in!

Can anyone create this issue with **Chrome / Edge** and try FireFox?

**Comment by jcansdale** [comment]
Hi @ttaylor29 👋 

It's really strange that it works with FireFox but not Chrome or Edge!

Is there an HTTP proxy between you and GitHub? Do you use a personal firewall or other security software?

Thanks!

**Comment by ttaylor29** [comment]
@jcansdale I was on my work computer when this occurred. Maybe they are blocking something? I can try later today maybe on my personal desktop!

**Comment by ttaylor29** [comment]
@jcansdale It works without any issues period on my personal desktop!

I'll try again on my work laptop and let you know. I can try the item from the other issue: https://github.com/github/VisualStudio/issues/2527#issuecomment-729637264

**Comment by ttaylor29** [comment]
Reference this for the answer:

https://github.com/github/VisualStudio/issues/2527#issuecomment-730082783
