### ISSUE TITLE
Cannot Install Visual Studio Extension on Visual Studo 2022 M1 Mac (Parralel Desktop) - Windows 11

### ISSUE THREAD

**Issue by chhinsras** [github/VisualStudio#2712]
I have Visual Studio 2022 running on Parralel Desktop with M1 arm64. 

Then I try to install extension like RDLC report designer, Github for VIsual Studio. Turn out, this shows this erorr. Any workaround

<img width="482" alt="Screenshot 2023-01-18 at 8 01 45 PM" src="https://user-images.githubusercontent.com/31751665/213178297-c84c4f92-9642-49ec-85cf-ddf8862c5f27.png">

```
1/18/2023 8:00:14 PM - Microsoft VSIX Installer
1/18/2023 8:00:14 PM - -------------------------------------------
1/18/2023 8:00:14 PM - vsixinstaller.exe version:
1/18/2023 8:00:14 PM - 17.4.2119
1/18/2023 8:00:14 PM - -------------------------------------------
1/18/2023 8:00:14 PM - Command line parameters:
1/18/2023 8:00:14 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\GitHub.VisualStudio-v2.11.106.vsix
1/18/2023 8:00:14 PM - -------------------------------------------
1/18/2023 8:00:14 PM - Microsoft VSIX Installer
1/18/2023 8:00:14 PM - -------------------------------------------
1/18/2023 8:00:15 PM - Initializing Install...
1/18/2023 8:00:15 PM - Extension Details...
1/18/2023 8:00:15 PM - 	Identifier         : c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
1/18/2023 8:00:15 PM - 	Name               : GitHub Extension for Visual Studio
1/18/2023 8:00:15 PM - 	Author             : GitHub, Inc
1/18/2023 8:00:15 PM - 	Version            : 2.11.106.19330
1/18/2023 8:00:15 PM - 	Description        : A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
1/18/2023 8:00:15 PM - 	Locale             : en-US
1/18/2023 8:00:15 PM - 	MoreInfoURL        : https://visualstudio.github.com/
1/18/2023 8:00:15 PM - 	InstalledByMSI     : False
1/18/2023 8:00:15 PM - 	SupportedFrameworkVersionRange : [4.5,)
1/18/2023 8:00:15 PM - 
1/18/2023 8:00:18 PM - 	SignatureState     : ValidSignature
1/18/2023 8:00:18 PM - 	SignedBy           : GitHub, Inc.
1/18/2023 8:00:18 PM - 	Certificate Info   : 
1/18/2023 8:00:18 PM - 		-------------------------------------------------------
1/18/2023 8:00:18 PM - 		[Subject]       : CN="GitHub, Inc.", O="GitHub, Inc.", L=San Francisco, S=California, C=US
1/18/2023 8:00:18 PM - 		[Issuer]        : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
1/18/2023 8:00:18 PM - 		[Serial Number] : 09144B52C8330F257D2512DAAAA1E545
1/18/2023 8:00:18 PM - 		[Not Before]    : 2/5/2020 7:00:00 AM
1/18/2023 8:00:18 PM - 		[Not After]     : 2/9/2023 7:00:00 PM
1/18/2023 8:00:18 PM - 		[Thumbprint]    : 9C5A6D389E1454F2ED9EE9419CDF743689709F9C
1/18/2023 8:00:18 PM - 
1/18/2023 8:00:18 PM - 	Supported Products : 
1/18/2023 8:00:18 PM - 		Microsoft.VisualStudio.Community
1/18/2023 8:00:18 PM - 			Version : [14.0,17.0)
1/18/2023 8:00:18 PM - 			ProductArchitecture : x86
1/18/2023 8:00:18 PM - 
1/18/2023 8:00:18 PM - 	References         : 
1/18/2023 8:00:18 PM - 		-------------------------------------------------------
1/18/2023 8:00:18 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
1/18/2023 8:00:18 PM - 		Name         : Visual Studio MPF 14.0
1/18/2023 8:00:18 PM - 		Version      : [14.0,)
1/18/2023 8:00:18 PM - 		MoreInfoURL  : 
1/18/2023 8:00:18 PM - 		Nested       : No
1/18/2023 8:00:18 PM - 
1/18/2023 8:00:18 PM - 	Prerequisites      : 
1/18/2023 8:00:18 PM - 		-------------------------------------------------------
1/18/2023 8:00:18 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/18/2023 8:00:18 PM - 		Name         : Visual Studio core editor
1/18/2023 8:00:18 PM - 		Version      : [15.0.25824.0,)
1/18/2023 8:00:18 PM - 
1/18/2023 8:00:18 PM - Signature Details...
1/18/2023 8:00:18 PM - 	Extension is signed with a valid signature.
1/18/2023 8:00:18 PM - 
1/18/2023 8:00:18 PM - Searching for applicable products...
1/18/2023 8:00:18 PM - Found installed product - Global Location
1/18/2023 8:00:18 PM - Found installed product - Visual Studio Professional 2022
1/18/2023 8:00:18 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by TheCodeTraveler** [comment]
I'm seeing the same error when trying to install the AWS Toolkit extension. I'm also on an M1 Mac running Parallels.

Note - I **am** able to use the AWS Toolkit Extension on Visual Studio when using an Intel-based MacBook Pro running Parallels.

<summary>
Error Log
<details>

1/24/2023 3:58:14 PM - Microsoft VSIX Installer
1/24/2023 3:58:14 PM - -------------------------------------------
1/24/2023 3:58:14 PM - vsixinstaller.exe version:
1/24/2023 3:58:14 PM - 17.4.2120
1/24/2023 3:58:14 PM - -------------------------------------------
1/24/2023 3:58:14 PM - Command line parameters:
1/24/2023 3:58:14 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\minnbran\Downloads\AWSToolkitPackage.v17.vsix
1/24/2023 3:58:14 PM - -------------------------------------------
1/24/2023 3:58:14 PM - Microsoft VSIX Installer
1/24/2023 3:58:14 PM - -------------------------------------------
1/24/2023 3:58:15 PM - Initializing Install...
1/24/2023 3:58:16 PM - Extension Details...
1/24/2023 3:58:16 PM - 	Identifier         : 0B82CB16-0E52-4363-9BC0-61E758689176
1/24/2023 3:58:16 PM - 	Name               : AWS Toolkit for Visual Studio 2022
1/24/2023 3:58:16 PM - 	Author             : Amazon Web Services
1/24/2023 3:58:16 PM - 	Version            : 1.38.0.0
1/24/2023 3:58:16 PM - 	Description        : The AWS Toolkit for Visual Studio is an extension for Microsoft Visual Studio on Windows that makes it easier for developers to develop, debug, and deploy .NET applications using Amazon Web Services.
1/24/2023 3:58:16 PM - 	Locale             : en-US
1/24/2023 3:58:16 PM - 	MoreInfoURL        : https://aws.amazon.com/visualstudio/
1/24/2023 3:58:16 PM - 	InstalledByMSI     : False
1/24/2023 3:58:16 PM - 	SupportedFrameworkVersionRange : [4.5,)
1/24/2023 3:58:16 PM - 
1/24/2023 3:58:19 PM - 	SignatureState     : ValidSignature
1/24/2023 3:58:19 PM - 	SignedBy           : Amazon.com, Inc.
1/24/2023 3:58:19 PM - 	Certificate Info   : 
1/24/2023 3:58:19 PM - 		-------------------------------------------------------
1/24/2023 3:58:19 PM - 		[Subject]       : CN="Amazon.com, Inc.", O="Amazon.com, Inc.", L=Seattle, S=Washington, C=US
1/24/2023 3:58:19 PM - 		[Issuer]        : CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1, O="DigiCert, Inc.", C=US
1/24/2023 3:58:19 PM - 		[Serial Number] : 0E4D3D377B5756257402C169EEED0D47
1/24/2023 3:58:19 PM - 		[Not Before]    : 9/27/2022 1:00:00 AM
1/24/2023 3:58:19 PM - 		[Not After]     : 9/28/2023 12:59:59 AM
1/24/2023 3:58:19 PM - 		[Thumbprint]    : ACFA520F8944C9B926BCDB567215434CD0201FDC
1/24/2023 3:58:19 PM - 
1/24/2023 3:58:19 PM - 	Supported Products : 
1/24/2023 3:58:19 PM - 		Microsoft.VisualStudio.Community
1/24/2023 3:58:19 PM - 			Version : [17.0,18.0)
1/24/2023 3:58:19 PM - 			ProductArchitecture : amd64
1/24/2023 3:58:19 PM - 
1/24/2023 3:58:19 PM - 	References         : 
1/24/2023 3:58:19 PM - 	Prerequisites      : 
1/24/2023 3:58:19 PM - 		-------------------------------------------------------
1/24/2023 3:58:19 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/24/2023 3:58:19 PM - 		Name         : Visual Studio core editor
1/24/2023 3:58:19 PM - 		Version      : [17.0,18.0)
1/24/2023 3:58:19 PM - 
1/24/2023 3:58:19 PM - Signature Details...
1/24/2023 3:58:19 PM - 	Extension is signed with a valid signature.
1/24/2023 3:58:19 PM - 
1/24/2023 3:58:19 PM - Searching for applicable products...
1/24/2023 3:58:19 PM - Found installed product - Visual Studio Enterprise 2022
1/24/2023 3:58:19 PM - Found installed product - Global Location
1/24/2023 3:58:19 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
</details>
</summary>

**Comment by chhinsras** [comment]
> 

Hi @brminnick , some extensions, I have installed by changing the product architecture to arm64. Yet, I am not lucky with RDLC report extension. Do you have any workarounds?

**Comment by Ocean-ZHY** [comment]
I also have this problem when installing the qt plugin in M1 mac, is there any solution?
