### ISSUE TITLE
Unable to login to the same account on multiple VMs

### ISSUE THREAD

**Issue by mponce1** [github/VisualStudio#284]
Steps to reproduce: 
1. Open Visual studio on 2 different VM's, not logged in on either
2. VM 1, login
3. VM 2, login
4. VM 1, create new local repository
5. VM 1, publish newly created repository (produces bad credentials error)
6. VM 1, publish a repository via manage connections -> github -> create (notice the dialog freezes)

Expected result: Each instance is treated individually without an issue to publishing and syncing. 
Actual result: After signing in on a separate VM, bad credentials error message. 

**Extension.log**

```
2016-05-03 12:38:57.0333|ERROR|thread:12|RepositoryPublishViewModel|Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 563
   at Octokit.Connection.<RunRequest>d__51.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 545
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__50`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\Connection.cs:line 530
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Post>d__17`1.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Http\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.RepositoriesClient.<Create>d__3.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\submodules\octokit.net\Octokit\Clients\RepositoriesClient.cs:line 90
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
2016-05-03 12:39:11.7812|INFO|thread: 1|RepositoryHost|Logged off of host 'https://api.github.com/'
2016-05-03 12:39:11.7968|INFO|thread: 1|LoginCache|Erasing the git credential cache for host 'https://github.com/'
```

![screen shot 2016-05-03 at 3 26 51 pm](https://cloud.githubusercontent.com/assets/6272408/15000861/ce2fd708-1147-11e6-8137-d85aaec35d1a.png)

**Comment by paladique** [comment]
Haven't been able to repro this, but will keep open in case someone else wants to try.

**Comment by grokys** [comment]
I thought this should have been fixed by passing a machine fingerprint to the API, but it seems we're had machine fingerprint support since before this issue was created.

**Comment by Haacked** [comment]
If we haven't been able to repro this and don't have any external issues (Halp or otherwise) we should probably close it.
