### ISSUE TITLE
VS crash with Null Reference Exception with GitHub extension installed

### ISSUE THREAD

**Issue by prasethu** [github/VisualStudio#29]
A customer reported consistent  crashes with the GitHub extension installed. It's a null reference exception in TeamExplorerServiceHolder.

Here's the dump with more info:
https://onedrive.live.com/redir?resid=439D1CEA375857EE!42116&authkey=!AGcdg_F0wdUwlTg&ithint=file%2cdmp

**Comment by shana** [comment]
We also have a report on an issue like this, and it looks like the IGitExt service is returning null for ActiveRepositories after a while of using VS. Not sure this is the same issue, but looks similar.

My internet isn't very good right now, can you post the stacktrace here?

**Comment by prasethu** [comment]
The mini dump did not have a StackTrace for some reason. 

The info I could gather is this:

<b>TargetSite</b>	{Microsoft.VisualStudio.TeamFoundation.Git.Extensibility.IGitRepositoryInfo <UIContextChanged>b__0()}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}

<b>DeclaringType</b>	{Name = "TeamExplorerServiceHolder" FullName = "GitHub.VisualStudio.Base.TeamExplorerServiceHolder"}	System.Type {System.RuntimeType}

<b>Source</b>	"GitHub.VisualStudio"

**Comment by shana** [comment]
Thanks, that helps :smile:

**Comment by MTBandolier** [comment]
I just hit what I assume is the same issue, when clicking the Manage Connections button on the TE toolbar.  Dump is [here](https://onedrive.live.com/redir?resid=F193F03516F59BA0!477316&authkey=!AF6lcxS9QliUsRk&ithint=folder%2c), in case it has info not available in the one @prasethu uploaded.

Here's the stack trace:

   at GitHub.VisualStudio.Base.TeamExplorerServiceHolder.<UIContextChanged>b__0() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\Base\TeamExplorerServiceHolder.cs:line 128
   at System.Threading.Tasks.Task`1.InnerInvoke() in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Future.cs:line 690
   at System.Threading.Tasks.Task.Execute() in f:\dd\ndp\clr\src\BCL\system\threading\Tasks\Task.cs:line 2498
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at GitHub.VisualStudio.Base.TeamExplorerServiceHolder.<UIContextChanged>d__2.MoveNext() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\Base\TeamExplorerServiceHolder.cs:line 128
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\AsyncMethodBuilder.cs:line 1018
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 954
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 901
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 890
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by shana** [comment]
@MTBandolier Thanks! That looks like the same issue as #23. It looks like the ActiveRepositories property returns null at some point, which is not something I would be expecting. I've done a new beta which hopefully resolves this issue, it's available from the releases page.

**Comment by shana** [comment]
Closed as dup of #23

**Comment by shana** [comment]
Fix released in v1.0.12.1
