### ISSUE TITLE
Clicking Pull Requests button in GitHub pane causes `ObjectDisposedException`

### ISSUE THREAD

**Issue by grokys** [github/VisualStudio#505]
On current master, if I have the GitHub pane open and click the "Pull Requests" button I get:

```
System.ObjectDisposedException occurred
  HResult=-2146232798
  Message=Cannot access a disposed object.
  ObjectName=""
  Source=System.Reactive.Linq
  StackTrace:
       at System.Reactive.Subjects.ReplaySubject`1.ReplayBufferBase.CheckDisposed()
       at System.Reactive.Subjects.ReplaySubject`1.ReplayBufferBase.OnCompleted()
       at System.Reactive.Subjects.ReplaySubject`1.OnCompleted()
       at GitHub.Collections.TrackingCollection`1.<Listen>b__36_2() in D:\projects\VisualStudio\src\GitHub.Exports.Reactive\Collections\TrackingCollection.cs:line 303
  InnerException: 
```

It doesn't happen every time. If it doesn't, close the pane and try again, or try restarting VS. After a few tries it should throw.

**Comment by grokys** [comment]
Might be caused by clicking it before the PR list has finished loading?

**Comment by grokys** [comment]
Another crasher: clicking it before the PR list finished loading threw this:

```
System.ArgumentOutOfRangeException occurred
  HResult=-2146233086
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  ParamName=index
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
       at System.Collections.Generic.List`1.get_Item(Int32 index)
       at GitHub.Collections.TrackingCollection`1.RecalculateFilter(IList`1 list, Int32 index, Int32 start, Int32 end, Boolean force) in D:\projects\VisualStudio\src\GitHub.Exports.Reactive\Collections\TrackingCollection.cs:line 895
  InnerException: 
```
