### ISSUE TITLE
Corrupted usage data is causing the extension to not load properly

### ISSUE THREAD

**Issue by shana** [github/VisualStudio#516]
> The last couple of days I get this error when starting Visual Studio: 
> The 'GitHubPackage' package did not load correctly.....
> 
> I re-installed the package, but that did not help.
> 
> The activity log of Visual Studio says the following: (any idea what the json error is?)

```
 <activity>
   <!-- ... -->
   <entry>
     <record>129</record>
     <time>2016/08/23 08:38:06.350</time>
     <type>Information</type>
     <source>VisualStudio</source>
     <description>Begin package load [GitHubPackage]</description>
     <guid>{C3D3DC68-C977-411F-B3E8-03B0DCCF7DFC}</guid>
   </entry>
   <entry>
     <record>130</record>
     <time>2016/08/23 08:38:06.525</time>
     <type>Error</type>
     <source>VisualStudio</source>
     <description>LegacySitePackage failed for package [GitHubPackage]Source: &apos;GitHub.Exports&apos; Description: Invalid JSON string
     System.Runtime.Serialization.SerializationException: Invalid JSON string
        at GitHub.SimpleJson.DeserializeObject(String json) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.Exports\SimpleJson.cs:line 544
        at GitHub.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.Exports\SimpleJson.cs:line 577
        at GitHub.SimpleJson.DeserializeObject[T](String json) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.Exports\SimpleJson.cs:line 595
        at GitHub.Services.UsageTracker.LoadUsage() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.Exports\Services\UsageTracker.cs:line 138
        at GitHub.Services.UsageTracker.IncrementLaunchCount() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.Exports\Services\UsageTracker.cs:line 73
        at GitHub.VisualStudio.GitHubPackage.Initialize() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\GitHubPackage.cs:line 57
        at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)
     </description>

     <guid>{C3D3DC68-C977-411F-B3E8-03B0DCCF7DFC}</guid>
     <hr>8013150c</hr>
     <errorinfo></errorinfo>
   </entry>
```

**Comment by IanByun** [comment]
I am having this issue as well
Any way to solve this?

**Comment by IanByun** [comment]
Getting "The 'GitHubPackage' package did not load correctly" error message on start-up
and getting "Invalid JSON string" when trying to login to GitHub via Team Explorer

**Comment by shana** [comment]
@IanByun Oh, I'm sorry, seems like the fix didn't make it to the latest release! There'll be a new release on Monday with it, but in the meantime, close VS and delete `%localappdata%\GitHubVisualStudio\ghfvs.usage`, that should fix it.

**Comment by IanByun** [comment]
@shana Great! Your solution fixed my VS. Thanks

**Comment by shana** [comment]
FYI, I just pushed out a new release v2.0.15.1 with a fix for this, so if you're getting hit by it, be sure to update!
