### ISSUE TITLE
Octokit.AuthorizationException crashed Visual Studio

### ISSUE THREAD

**Issue by femisimon** [github/VisualStudio#633]
# Description

Windows 8 VM put to sleep over the weekend, launched OS on the third day (Monday). Opened Visual Studio and double clicked on a repo listed on **Local Git Repositories** that is hosted on GitHub. That action crashed Visual Studio, below is the log provided by Windows:
- GitHub Extension version: v2.0.15.1 
  - Visual Studio version: Professional 2015

```
Problem signature:
  Problem Event Name:   CLR20r3
Problem Signature 01:   devenv.exe
  Problem Signature 02: 14.0.25420.1
  Problem Signature 03: 57685d85
  Problem Signature 04: Octokit
  Problem Signature 05: 0.20.0.0
  Problem Signature 06: 57caa119
  Problem Signature 07: 1072
  Problem Signature 08: 14
  Problem Signature 09: Octokit.AuthorizationException
  OS Version:   6.3.9600.2.0.0.256.48
  Locale ID:    1033
  Additional Information 1: 5861
  Additional Information 2: 5861822e1919d7c014bbb064c64908b2
  Additional Information 3: a10f
  Additional Information 4: a10ff7d2bb2516fdc753f9c34fc3b069
```

**Comment by femisimon** [comment]
I just reproduced within 24hour. Visual Studio crashes.

**Steps to reproduce**
- Launch Visual Studio
- Login to GHfVS
- Leave Visual studio and sleep Windows OS for 24hours
- double click on a repo listed on Local Git Repositories that is hosted on GitHub

**Expected** -  Repo clicked should be switched to and highlighted on GitHub section on the Team Explorer pane.

**Actual** -  Visual studio crashed.

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	devenv.exe
  Application Version:	14.0.25420.1
  Application Timestamp:	57685d85
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.3.9600.17415
  Fault Module Timestamp:	54504ade
  Exception Code:	e0434352
  Exception Offset:	00014598
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	a10f
  Additional Information 4:	a10ff7d2bb2516fdc753f9c34fc3b069
```

![snip20161025_90](https://cloud.githubusercontent.com/assets/17054747/19697745/7006bcc6-9aa1-11e6-9c1f-248f9983363d.png)

**Comment by shana** [comment]
@femisimon The local git repositories area is not ours, can't tell if this is us crashing or not. Can you uninstall the extension and go through the same steps to see what it does please?

**Comment by tocsoft** [comment]
I've managed to reproduce this error, definitely a GHfVS issue.

**Steps to reproduce:**
 1. Login to GHfVS.
 2. Open any local repo (doesn't matter if its hosted on github or not).
 3. revoke the GHfVS access token via github.com
 4. switch repo to another hosted on github (you can even switch to a none hosted repo first but as soon as you switch to a hosted on it dies)

**Steps to reproduce:**
 1. Login to GHfVS.
 2. Open any local repo (doesn't matter if its hosted on github or not).
 3. revoke the GHfVS access token via github.com
 4. switch to a local repo(not hosted on github)
 5. switch repo to repo hosted on github

```
Octokit.AuthorizationException was unhandled
Message: An unhandled exception of type 'Octokit.AuthorizationException' occurred in WindowsBase.dll
```

Debug output log (had been cleared just prior to crash)
```
System.Windows.Data Error: 40 : BindingExpression path error: 'SectionCommands' property not found on 'object' ''GitHubHomeSection' (HashCode=62155537)'. BindingExpression:Path=Section.SectionCommands; DataItem='TeamExplorerSectionHost' (HashCode=54833981); target element is 'SectionControl' (Name='thisSectionControl'); target property is 'SectionCommands' (type 'IEnumerable`1')
Stopping PullRequests (5590693)
Firing Finish from PRList (5590693)
Firing Finish from PRList for flow PullRequests (5590693)
Firing Next from End (5590693)
Firing Next from End for flow PullRequests (5590693)
The thread 0x4958 has exited with code 0 (0x0).
Disposing (5590693)
The thread 0x4e2c has exited with code 0 (0x0).
Start (16918750)
Firing Next from None (16918750)
Firing Next from None for flow PullRequests (16918750)
The thread 0x3a10 has exited with code 0 (0x0).
The thread 0x2bbc has exited with code 0 (0x0).
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.UserControl', AncestorLevel='1''. BindingExpression:Path=FontFamily; DataItem=null; target element is 'FlowDocument' (HashCode=38798339); target property is 'FontFamily' (type 'FontFamily')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.UserControl', AncestorLevel='1''. BindingExpression:Path=FontSize; DataItem=null; target element is 'FlowDocument' (HashCode=38798339); target property is 'FontSize' (type 'Double')
The thread 0x29a4 has exited with code 0 (0x0).
The thread 0x17cc has exited with code 0 (0x0).
The program '[17240] devenv.exe: Program Trace' has exited with code 0 (0x0).
The program '[17240] devenv.exe' has exited with code 0 (0x0).

```
Stacktrace (not sure how I managed to get this to log out but to was there after one crash)
```
<TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical">
   <TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier>
   <Description>Unhandled exception</Description>
   <AppDomain>DefaultDomain</AppDomain>
   <Exception>
      <ExceptionType>Octokit.AuthorizationException, Octokit, Version=0.22.0.0, Culture=neutral, PublicKeyToken=5525be5bc50478ea</ExceptionType>
      <Message>Bad credentials</Message>
      <StackTrace>at Octokit.Connection.HandleErrors(IResponse response) in C:\Users\tocsoft\Documents\GitHubVisualStudio\VisualStudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 577
   at Octokit.Connection.&amp;lt;RunRequest&amp;gt;d__53.MoveNext() in C:\Users\tocsoft\Documents\GitHubVisualStudio\VisualStudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 558
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.&amp;lt;Run&amp;gt;d__52`1.MoveNext() in C:\Users\tocsoft\Documents\GitHubVisualStudio\VisualStudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 543
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.ExceptionHelpers.Throw(Exception exception)
   at System.Reactive.Stubs.&amp;lt;&amp;gt;c.&amp;lt;.cctor&amp;gt;b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.ScheduledObserver`1.Run(Object state, Action`1 recurse)
   at System.Reactive.Concurrency.Scheduler.&amp;lt;&amp;gt;c__DisplayClass65_0`1.&amp;lt;InvokeRec1&amp;gt;b__0(TState state1)
   at System.Reactive.Concurrency.Scheduler.InvokeRec1[TState](IScheduler scheduler, Pair`2 pair)
   at System.Reactive.Concurrency.DispatcherScheduler.&amp;lt;&amp;gt;c__DisplayClass12_0`1.&amp;lt;Schedule&amp;gt;b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)</StackTrace>
      <ExceptionString>Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in C:\Users\tocsoft\Documents\GitHubVisualStudio\VisualStudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 577
   at Octokit.Connection.&amp;lt;RunRequest&amp;gt;d__53.MoveNext() in C:\Users\tocsoft\Documents\GitHubVisualStudio\VisualStudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 558
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.&amp;lt;Run&amp;gt;d__52`1.MoveNext() in C:\Users\tocsoft\Documents\GitHubVisualStudio\VisualStudio\submodules\octokit.net\Octokit\Http\Connection.cs:line 543
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.ExceptionHelpers.Throw(Exception exception)
   at System.Reactive.Stubs.&amp;lt;&amp;gt;c.&amp;lt;.cctor&amp;gt;b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.ScheduledObserver`1.Run(Object state, Action`1 recurse)
   at System.Reactive.Concurrency.Scheduler.&amp;lt;&amp;gt;c__DisplayClass65_0`1.&amp;lt;InvokeRec1&amp;gt;b__0(TState state1)
   at System.Reactive.Concurrency.Scheduler.InvokeRec1[TState](IScheduler scheduler, Pair`2 pair)
   at System.Reactive.Concurrency.DispatcherScheduler.&amp;lt;&amp;gt;c__DisplayClass12_0`1.&amp;lt;Schedule&amp;gt;b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp;amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}</ExceptionString>
      <DataItems>
         <Data />
      </DataItems>
   </Exception>
</TraceRecord>
```

**Comment by tocsoft** [comment]
ok done more digging around on whats causing the crash.

Basically there is an uncaught  `AuthorizationException` when trying to download the list of PRs for a repo.

[`repositoryHost.ModelService.GetPullRequests(repository, pullRequests);` in `PullRequestListViewModel`](https://github.com/github/VisualStudio/blob/183af5d/src/GitHub.App/ViewModels/PullRequestListViewModel.cs#L102) is the initial caller causing an exception to be thrown buy client api call [`apiClient.GetPullRequestsForRepository(repo.CloneUrl.Owner, repo.CloneUrl.RepositoryName)` in `ModelService` on Line 163](https://github.com/github/VisualStudio/blob/183af5d/src/GitHub.App/Services/ModelService.cs#L163)

the fix is obviously handle the exception.

I would have thought the preference would be in the `PullRequestListViewModel` so the 'not logged in' state can be tracked and passwords can be re-prompted for, or at least show as error message in an info box.

The problem is that I can't seem to catch the exception in the `PullRequestListViewModel`'s `Initialize()` method because `TrackingCollection<IPullRequestModel>` is re-throwing the exception in some disconnected background way that I can seem to find a way to catch.

A quick/dirty fix to stop the hard crash is just catch the exception [in `ModelService` on Line 175 ](https://github.com/github/VisualStudio/blob/183af5d/src/GitHub.App/Services/ModelService.cs#L175 ) by adding a `.Catch<IPullRequestModel, AuthorizationException>(.....)` and basically swollowing the exception but that feels all sorts of wrong.

**Comment by shana** [comment]
We should totally not even reach this point at all, login checks should have been done earlier, but maybe nothing else kicked in that actually talked to the API to validate the login, so I can see how we end up with this problem 😞 

So, if we get login exceptions using credentials that we assumed were good, we need to logout the host so that the UI goes back to the logged out view. Logging out the `RepositoryHost` will trigger https://github.com/github/VisualStudio/blob/master/src/GitHub.VisualStudio/UI/Views/GitHubPaneViewModel.cs#L96, which will force the UI to reload and show the logged out view, so this should be straightforward.
