### ISSUE TITLE
Cannot Uninstall in order to update

### ISSUE THREAD

**Issue by tebeco** [github/VisualStudio#806]
- GitHub Extension for Visual Studio  version: 'GitHub Extension for Visual Studio', version 2.1.1.4.
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26020.0 D15REL
Microsoft .NET Framework
Version 4.7.02021

__What happened__ (with steps, logs and screenshots, if possible)
* Trying to update to v2.2.x 
* Failed with "Extension already installed"
* Tried to uninstall, got this error :

```
27/01/2017 13:07:49 - Microsoft VSIX Installer
27/01/2017 13:07:49 - -------------------------------------------
27/01/2017 13:07:49 - vsixinstaller.exe version:
27/01/2017 13:07:49 - 15.0.26020.0 built by: D15REL
27/01/2017 13:07:49 - -------------------------------------------
27/01/2017 13:07:49 - Command line parameters:
27/01/2017 13:07:49 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:15.0.26020.0,/appidname:Microsoft Visual Studio Enterprise 2017 RC,/u:c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
27/01/2017 13:07:49 - -------------------------------------------
27/01/2017 13:07:49 - Microsoft VSIX Installer
27/01/2017 13:07:49 - -------------------------------------------
27/01/2017 13:07:52 - Initializing Uninstall...
27/01/2017 13:07:52 - Détails de l'extension...
27/01/2017 13:07:52 - 	Identifier         : c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
27/01/2017 13:07:52 - 	Name               : GitHub Extension for Visual Studio
27/01/2017 13:07:52 - 	Author             : GitHub, Inc
27/01/2017 13:07:52 - 	Version            : 2.1.1.4
27/01/2017 13:07:52 - 	Description        : A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
27/01/2017 13:07:52 - 	Locale             : en-US
27/01/2017 13:07:52 - 	MoreInfoURL        : https://visualstudio.github.com/
27/01/2017 13:07:52 - 	InstalledByMSI     : False
27/01/2017 13:07:52 - 	SupportedFrameworkVersionRange : [4.5,)
27/01/2017 13:07:52 - 
27/01/2017 13:07:52 - 	Produits pris en charge : 
27/01/2017 13:07:52 - 		Microsoft.VisualStudio.Community
27/01/2017 13:07:52 - 			Version : [14.0,15.0]
27/01/2017 13:07:52 - 
27/01/2017 13:07:52 - 	Références         : 
27/01/2017 13:07:52 - 		-------------------------------------------------------
27/01/2017 13:07:52 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
27/01/2017 13:07:52 - 		Name         : Visual Studio MPF 14.0
27/01/2017 13:07:52 - 		Version      : [14.0,)
27/01/2017 13:07:52 - 		MoreInfoURL  : 
27/01/2017 13:07:52 - 		Nested       : No
27/01/2017 13:07:52 - 
27/01/2017 13:07:52 - 	Prérequis          : 
27/01/2017 13:07:52 - 		-------------------------------------------------------
27/01/2017 13:07:52 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
27/01/2017 13:07:52 - 		Name         : Visual Studio core editor
27/01/2017 13:07:52 - 		Version      : [15.0.25824.0,16.0)
27/01/2017 13:07:52 - 
27/01/2017 13:07:52 - 
27/01/2017 13:08:07 - Les produits cibles suivants ont été sélectionnés...
27/01/2017 13:08:07 - 	Microsoft Visual Studio Enterprise 2017 RC
27/01/2017 13:08:07 - 
27/01/2017 13:08:09 - Désinstallation de 'GitHub Extension for Visual Studio', version 2.1.1.4.
27/01/2017 13:08:09 - System.IO.FileNotFoundException: Unable to find the specified file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension, Boolean markAsPackComponent)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)

```

**Comment by shana** [comment]
@tebeco The 2017 vsix installer has/had some issues, and in some cases ends up corrupting the extension catalog, causing these problems, unfortunately 😢 

To manually remove the extension and reset the catalog so it's happy, the best thing to do is probably the following: 

- Close all instances of VS
- Go to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\` and do a search for `GitHub.VisualStudio.dll`. All the directories that contain a file with that name are installations of GHfVS (as VS never actually removes them, but just disables them...).
- Delete all the directories, or alternatively move them to another location (and not anything else, be careful on what you delete or move).
- Open a Visual Studio 2017 developer command line as administrator (right click on the shortcut, `Run as administrator`)
- run `devenv /setup` on that command line to refresh the VS catalog. This will take some time, wait it out.

All copies of the extension should be cleared after this, and you should be able to install the newest version without further problems.

**Comment by shana** [comment]
@tebeco I mistyped the path to the visual studio installation in my initial comment, sorry! The correct path is `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions`, I've updated the instructions to match

**Comment by tebeco** [comment]
i've cut/past the folder of GHfVS in a personnal folder

`devenv.exe /setup` took few minutes, did not open or print anything ?
I guess it's fine

I've tried to re run `GitHub.VisualStudio.vsix`

Still getting :

```---------------------------
VSIX Installer
---------------------------
This extension is already installed to all applicable products.
---------------------------
OK   
---------------------------
```

**Comment by tebeco** [comment]
I've opened VS2017, I don't have anymore GHfVS
And I cannot install it anymore, it download it, and after I close VS, it tells me it can install on VS2017 and then while installing it crash on :

```
27/01/2017 14:31:16 - Microsoft VSIX Installer
27/01/2017 14:31:16 - -------------------------------------------
27/01/2017 14:31:16 - vsixinstaller.exe version:
27/01/2017 14:31:16 - 15.0.26020.0 built by: D15REL
27/01/2017 14:31:16 - -------------------------------------------
27/01/2017 14:31:16 - Command line parameters:
27/01/2017 14:31:16 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:15.0.26020.0,/appidname:Microsoft Visual Studio Enterprise 2017 RC,C:\Users\ahert\AppData\Local\Temp\VSIXdvfr2ee1.vsix
27/01/2017 14:31:16 - -------------------------------------------
27/01/2017 14:31:16 - Microsoft VSIX Installer
27/01/2017 14:31:16 - -------------------------------------------
27/01/2017 14:31:17 - Initializing Install...
27/01/2017 14:31:17 - Détails de l'extension...
27/01/2017 14:31:17 - 	Identifier         : c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
27/01/2017 14:31:17 - 	Name               : GitHub Extension for Visual Studio
27/01/2017 14:31:17 - 	Author             : GitHub, Inc
27/01/2017 14:31:17 - 	Version            : 2.2.0.5
27/01/2017 14:31:17 - 	Description        : A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
27/01/2017 14:31:17 - 	Locale             : en-US
27/01/2017 14:31:17 - 	MoreInfoURL        : https://visualstudio.github.com/
27/01/2017 14:31:17 - 	InstalledByMSI     : False
27/01/2017 14:31:17 - 	SupportedFrameworkVersionRange : [4.5,)
27/01/2017 14:31:17 - 
27/01/2017 14:31:18 - 	SignatureState     : ValidSignature
27/01/2017 14:31:18 - 	SignedBy           : GitHub, Inc.
27/01/2017 14:31:18 - 	Certificate Info   : 
27/01/2017 14:31:18 - 		-------------------------------------------------------
27/01/2017 14:31:18 - 		[Subject]       : CN="GitHub, Inc.", O="GitHub, Inc.", L=San Francisco, S=California, C=US
27/01/2017 14:31:18 - 		[Issuer]        : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
27/01/2017 14:31:18 - 		[Serial Number] : 013AA7BBB950DCCD25305F1602258B00
27/01/2017 14:31:18 - 		[Not Before]    : 23/11/2016 01:00:00
27/01/2017 14:31:18 - 		[Not After]     : 19/11/2019 13:00:00
27/01/2017 14:31:18 - 		[Thumbprint]    : C4FDF13659F49E57AC14774FDF45053F499F185F
27/01/2017 14:31:18 - 
27/01/2017 14:31:18 - 	Produits pris en charge : 
27/01/2017 14:31:18 - 		Microsoft.VisualStudio.Community
27/01/2017 14:31:18 - 			Version : [14.0,15.0]
27/01/2017 14:31:18 - 
27/01/2017 14:31:18 - 	Références         : 
27/01/2017 14:31:18 - 		-------------------------------------------------------
27/01/2017 14:31:18 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
27/01/2017 14:31:18 - 		Name         : Visual Studio MPF 14.0
27/01/2017 14:31:18 - 		Version      : [14.0,)
27/01/2017 14:31:18 - 		MoreInfoURL  : 
27/01/2017 14:31:18 - 		Nested       : No
27/01/2017 14:31:18 - 
27/01/2017 14:31:18 - 	Prérequis          : 
27/01/2017 14:31:18 - 		-------------------------------------------------------
27/01/2017 14:31:18 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
27/01/2017 14:31:18 - 		Name         : Visual Studio core editor
27/01/2017 14:31:18 - 		Version      : [15.0.25824.0,16.0)
27/01/2017 14:31:18 - 
27/01/2017 14:31:18 - Détails de la signature...
27/01/2017 14:31:18 - 	Extension is signed with a valid signature.
27/01/2017 14:31:18 - 
27/01/2017 14:31:20 - L'extension ayant l'ID 'c3d3dc68-c977-411f-b3e8-03b0dccf7dfc' n'est installée dans Microsoft Visual Studio Enterprise 2017 RC.
27/01/2017 14:31:33 - Les produits cibles suivants ont été sélectionnés...
27/01/2017 14:31:33 - 	Microsoft Visual Studio Enterprise 2017 RC
27/01/2017 14:31:33 - 
27/01/2017 14:31:35 - Début de l'installation de l'extension dans Microsoft Visual Studio Enterprise 2017 RC...
27/01/2017 14:31:35 - Erreur d'installation : System.IO.FileNotFoundException: Unable to find the specified file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
27/01/2017 14:31:35 - VSIX TaskScheduler : VSIX Auto Updatetask existe déjà.

```

**Comment by tebeco** [comment]
FYI :
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions`
Search for `GitHub.VisualStudio.dll` ==> 0 Match

**Comment by shana** [comment]
@tebeco So VS 2017 runs without errors, and the extension is not listed in `Extensions and Updates/Installed`, correct? Can you try downloading the extension from https://ghfvs-installer.github.com/releases/2.2.0.5/GitHub.VisualStudio.vsix, and double clicking on that to install it instead of installing it through the gallery?

@aarnott Any clues as to what this error means?

**Comment by jcansdale** [comment]
@tebeco,

Could you try running the following from the command line:
```
set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE;%PATH%
vsixinstaller /q /u:"c3d3dc68-c977-411f-b3e8-03b0dccf7dfc" /l:GH4VS.log
type %temp%\GH4VS.log
```

I'd be interested to see what the log file says.

**Comment by tebeco** [comment]
installing from Visual Studio give my this :

![image](https://cloud.githubusercontent.com/assets/2266487/22380057/4500f888-e4bc-11e6-9a9d-55fbd796d4db.png)

![image](https://cloud.githubusercontent.com/assets/2266487/22380061/48c5b238-e4bc-11e6-8db1-e1598a21d95a.png)

```
27/01/2017 18:12:36 - Microsoft VSIX Installer
27/01/2017 18:12:36 - -------------------------------------------
27/01/2017 18:12:36 - vsixinstaller.exe version:
27/01/2017 18:12:36 - 15.0.26020.0 built by: D15REL
27/01/2017 18:12:36 - -------------------------------------------
27/01/2017 18:12:36 - Command line parameters:
27/01/2017 18:12:36 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:15.0.26020.0,/appidname:Microsoft Visual Studio Enterprise 2017 RC,C:\Users\ahert\AppData\Local\Temp\VSIXo0dqgymo.vsix
27/01/2017 18:12:36 - -------------------------------------------
27/01/2017 18:12:36 - Microsoft VSIX Installer
27/01/2017 18:12:36 - -------------------------------------------
27/01/2017 18:12:36 - Initializing Install...
27/01/2017 18:12:36 - Détails de l'extension...
27/01/2017 18:12:36 - 	Identifier         : c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
27/01/2017 18:12:36 - 	Name               : GitHub Extension for Visual Studio
27/01/2017 18:12:36 - 	Author             : GitHub, Inc
27/01/2017 18:12:36 - 	Version            : 2.2.0.5
27/01/2017 18:12:36 - 	Description        : A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
27/01/2017 18:12:36 - 	Locale             : en-US
27/01/2017 18:12:36 - 	MoreInfoURL        : https://visualstudio.github.com/
27/01/2017 18:12:36 - 	InstalledByMSI     : False
27/01/2017 18:12:36 - 	SupportedFrameworkVersionRange : [4.5,)
27/01/2017 18:12:36 - 
27/01/2017 18:12:37 - 	SignatureState     : ValidSignature
27/01/2017 18:12:37 - 	SignedBy           : GitHub, Inc.
27/01/2017 18:12:37 - 	Certificate Info   : 
27/01/2017 18:12:37 - 		-------------------------------------------------------
27/01/2017 18:12:37 - 		[Subject]       : CN="GitHub, Inc.", O="GitHub, Inc.", L=San Francisco, S=California, C=US
27/01/2017 18:12:37 - 		[Issuer]        : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
27/01/2017 18:12:37 - 		[Serial Number] : 013AA7BBB950DCCD25305F1602258B00
27/01/2017 18:12:37 - 		[Not Before]    : 23/11/2016 01:00:00
27/01/2017 18:12:37 - 		[Not After]     : 19/11/2019 13:00:00
27/01/2017 18:12:37 - 		[Thumbprint]    : C4FDF13659F49E57AC14774FDF45053F499F185F
27/01/2017 18:12:37 - 
27/01/2017 18:12:37 - 	Produits pris en charge : 
27/01/2017 18:12:37 - 		Microsoft.VisualStudio.Community
27/01/2017 18:12:37 - 			Version : [14.0,15.0]
27/01/2017 18:12:37 - 
27/01/2017 18:12:37 - 	Références         : 
27/01/2017 18:12:37 - 		-------------------------------------------------------
27/01/2017 18:12:37 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
27/01/2017 18:12:37 - 		Name         : Visual Studio MPF 14.0
27/01/2017 18:12:37 - 		Version      : [14.0,)
27/01/2017 18:12:37 - 		MoreInfoURL  : 
27/01/2017 18:12:37 - 		Nested       : No
27/01/2017 18:12:37 - 
27/01/2017 18:12:37 - 	Prérequis          : 
27/01/2017 18:12:37 - 		-------------------------------------------------------
27/01/2017 18:12:37 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
27/01/2017 18:12:37 - 		Name         : Visual Studio core editor
27/01/2017 18:12:37 - 		Version      : [15.0.25824.0,16.0)
27/01/2017 18:12:37 - 
27/01/2017 18:12:37 - Détails de la signature...
27/01/2017 18:12:37 - 	Extension is signed with a valid signature.
27/01/2017 18:12:37 - 
27/01/2017 18:12:39 - L'extension ayant l'ID 'c3d3dc68-c977-411f-b3e8-03b0dccf7dfc' n'est installée dans Microsoft Visual Studio Enterprise 2017 RC.
27/01/2017 18:12:53 - Les produits cibles suivants ont été sélectionnés...
27/01/2017 18:12:53 - 	Microsoft Visual Studio Enterprise 2017 RC
27/01/2017 18:12:53 - 
27/01/2017 18:12:55 - Début de l'installation de l'extension dans Microsoft Visual Studio Enterprise 2017 RC...
27/01/2017 18:12:55 - VSIX TaskScheduler : VSIX Auto Updatetask existe déjà.
27/01/2017 18:12:55 - Erreur d'installation : System.IO.FileNotFoundException: Unable to find the specified file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

```

**Comment by tebeco** [comment]
then i went AGAIN inside :
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions`  <== is this the right folder ?
Still no match for "GitHub.VisualStudio.dll"
Vs2017 does not detect installed or update anything about the extension (only online research)

And then Typing thing :

`vsixinstaller /q /u:"c3d3dc68-c977-411f-b3e8-03b0dccf7dfc" /l:GH4VS.log`

it output different log depending on different tries ...
* but it's either previous log (GUID not found)
* or detect the vs2015 extension only


my last try gave :
```
27/01/2017 18:20:15 - Microsoft VSIX Installer
27/01/2017 18:20:15 - -------------------------------------------
27/01/2017 18:20:15 - vsixinstaller.exe version:
27/01/2017 18:20:15 - 15.0.26020.0 built by: D15REL
27/01/2017 18:20:15 - -------------------------------------------
27/01/2017 18:20:15 - Command line parameters:
27/01/2017 18:20:15 - vsixinstaller,/q,/u:c3d3dc68-c977-411f-b3e8-03b0dccf7dfc,/l:GH4VS.log
27/01/2017 18:20:15 - -------------------------------------------
27/01/2017 18:20:15 - Microsoft VSIX Installer
27/01/2017 18:20:15 - -------------------------------------------
27/01/2017 18:20:19 - Microsoft.VisualStudio.ExtensionManager.NotInstalledException: L'extension avec l'identificateur 'c3d3dc68-c977-411f-b3e8-03b0dccf7dfc' n'est installée sur aucun des produits actuellement installés.
   at VSIXInstaller.App.GetUninstallableData(String vsixId, IEnumerable`1& targetSkus)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.OnStartup(StartupEventArgs e)

```


(FYI, i'll be back in 12h for testing new idea here)

**Comment by shana** [comment]
@tebeco The only thing I can think of is that 2017 is not playing nice with the installation of 2015 you have in the same machine, most likely due to the VS installer bugs in the previous versions of the RC. Try uninstalling all versions from 2015 before installing the extension again, see if that fixes it.

**Comment by tebeco** [comment]
I wonder why I didn't try that ;)
I'll ping you here once I've tried (i hope tonight)

**Comment by AArnott** [comment]
I haven't read all of this thread, but it could be that an older version of the github extension corrupted your VS installer's manifest of what you have installed. The only known workaround we have for that is to uninstall, then reinstall VS 2017. I'm not sure if you already tried that though.

**Comment by tebeco** [comment]
Github Extension was allready uninstalled from VS2015
So I took the same step as the one for VS2017
Went to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions`
And found 10 matching folder that contained `GitHub.VisualStudio.dll`
So i've move them somewhere else

At the same time, it seems that VS2017 just detected an update so i'll keep you posted here

**Comment by tebeco** [comment]
@AArnott, no need to uninstall & reinstall VS2017
@shana thx it seems that it worked
The VSIX detected both VS2015 & VS2017 this time

The only thing that did not work is VS2017 update ;)
especial Azure stuff
Anyway thank :)

**Comment by rubenscholfield** [comment]
Xan i fork you for Futuretecnologies?

**Comment by shana** [comment]
@tebeco Awesome, thanks for the update and for the patience, good to know that there's a way out without reinstalling VS completely 😄

**Comment by tebeco** [comment]
good news ... just re updated VS2017 + GHfVS 2.2.0.6, just worked perfectly
