### ISSUE TITLE
CompositionContractMismatchException when I open GitHubVS.sln directly

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#976]
- GitHub Extension for Visual Studio version: 2.2.1.0 (experimental)
- Visual Studio version: 2015

__What happened__ (with steps, logs and screenshots, if possible)

I opened the `GitHubVS.sln` and started experiencing random exceptions similar to this:

```
System.ComponentModel.Composition.CompositionContractMismatchException:
    Cannot cast the underlying exported value of type
    'Microsoft.VisualStudio.Composition.NetFxAdapters+MefV1ExportProvider+
      ComposablePartForExportFactory' to type 'Microsoft.TeamFoundation.Controls.ITeamExplorerSection'.
   at System.ComponentModel.Composition.ExportServices.CastExportedValue[T](ICompositionElement element, Object exportedValue)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass6_0`2.<CreateStronglyTypedExportFactoryOfTM>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```

**Comment by jcansdale** [comment]
This is a strange and tricky to track down issue that is caused by dependencies from the opened solution being loaded into Visual Studio! It only seems to happen when Visual Studio is launched by opening a .sln file. The problem assemblies are copied to and loaded from the following location: `%LOCALAPPDATA%\Microsoft\VisualStudio\14.0\ProjectAssemblies`.

The fix is to ensure that any required assembly resolution is done before Visual Studio's project system has a chance to mess things up. The `TryAddPriorityAssemblyResolve` method is what does this.
https://github.com/github/VisualStudio/pull/970/files#diff-12f933fbcb54af34ee67452d94924a4eR52

I accidentally disabled this method while refactoring and started seeing these exceptions again. I thought it would be a good idea to capture it here in case it ever starts happening again!

See also #923.
