### ISSUE TITLE
Extension 2.2.0.11 fails to instal on Visual Studio 15.2.16430.4

### ISSUE THREAD

**Issue by paulomorgado** [github/VisualStudio#987]
- GitHub Extension for Visual Studio  version: 2.2.0.11
- Visual Studio version: Visual Studio Enterprise 2017 15.2 (16430.4) Release

The extension fails to install with the following log:

```
10/05/2017 22:03:18 - Microsoft VSIX Installer
10/05/2017 22:03:18 - -------------------------------------------
10/05/2017 22:03:18 - vsixinstaller.exe version:
10/05/2017 22:03:18 - 15.0.26430.4 built by: D15SVC
10/05/2017 22:03:18 - -------------------------------------------
10/05/2017 22:03:18 - Command line parameters:
10/05/2017 22:03:18 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:15.0.26430.4,/appidname:Microsoft Visual Studio Enterprise 2017,C:\Users\Paulo\AppData\Local\Temp\VSIXtz0k1avf.vsix,/installas:2436,/callingprocessid:33028
10/05/2017 22:03:18 - -------------------------------------------
10/05/2017 22:03:18 - Microsoft VSIX Installer
10/05/2017 22:03:18 - -------------------------------------------
10/05/2017 22:03:22 - Initializing Install...
10/05/2017 22:03:25 - Extension Details...
10/05/2017 22:03:25 - 	Identifier         : c3d3dc68-c977-411f-b3e8-03b0dccf7dfc
10/05/2017 22:03:25 - 	Name               : GitHub Extension for Visual Studio
10/05/2017 22:03:25 - 	Author             : GitHub, Inc
10/05/2017 22:03:25 - 	Version            : 2.2.0.11
10/05/2017 22:03:25 - 	Description        : A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
10/05/2017 22:03:25 - 	Locale             : en-US
10/05/2017 22:03:25 - 	MoreInfoURL        : https://visualstudio.github.com/
10/05/2017 22:03:25 - 	InstalledByMSI     : False
10/05/2017 22:03:25 - 	SupportedFrameworkVersionRange : [4.5,)
10/05/2017 22:03:25 - 
10/05/2017 22:03:28 - 	SignatureState     : ValidSignature
10/05/2017 22:03:28 - 	SignedBy           : GitHub, Inc.
10/05/2017 22:03:28 - 	Certificate Info   : 
10/05/2017 22:03:28 - 		-------------------------------------------------------
10/05/2017 22:03:28 - 		[Subject]       : CN="GitHub, Inc.", O="GitHub, Inc.", L=San Francisco, S=California, C=US
10/05/2017 22:03:28 - 		[Issuer]        : CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
10/05/2017 22:03:28 - 		[Serial Number] : 013AA7BBB950DCCD25305F1602258B00
10/05/2017 22:03:28 - 		[Not Before]    : 23/11/2016 00:00:00
10/05/2017 22:03:28 - 		[Not After]     : 19/11/2019 12:00:00
10/05/2017 22:03:28 - 		[Thumbprint]    : C4FDF13659F49E57AC14774FDF45053F499F185F
10/05/2017 22:03:28 - 
10/05/2017 22:03:28 - 	Supported Products : 
10/05/2017 22:03:28 - 		Microsoft.VisualStudio.Community
10/05/2017 22:03:28 - 			Version : [14.0,15.0]
10/05/2017 22:03:28 - 
10/05/2017 22:03:28 - 	References         : 
10/05/2017 22:03:28 - 		-------------------------------------------------------
10/05/2017 22:03:28 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
10/05/2017 22:03:28 - 		Name         : Visual Studio MPF 14.0
10/05/2017 22:03:28 - 		Version      : [14.0,)
10/05/2017 22:03:28 - 		MoreInfoURL  : 
10/05/2017 22:03:28 - 		Nested       : No
10/05/2017 22:03:28 - 
10/05/2017 22:03:28 - 	Prerequisites      : 
10/05/2017 22:03:28 - 		-------------------------------------------------------
10/05/2017 22:03:28 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
10/05/2017 22:03:28 - 		Name         : Visual Studio core editor
10/05/2017 22:03:28 - 		Version      : [15.0.25824.0,16.0)
10/05/2017 22:03:28 - 
10/05/2017 22:03:28 - Signature Details...
10/05/2017 22:03:28 - 	Extension is signed with a valid signature.
10/05/2017 22:03:28 - 
10/05/2017 22:03:29 - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\master.pkgdef

10/05/2017 22:03:29 - PKGDEF Information: Creating PkgDefCacheNonVolatile
10/05/2017 22:03:29 - PKGDEF Information: Double-checking master pkgdef file
10/05/2017 22:03:29 - PKGDEF Information: PkgDefManagement initialized
10/05/2017 22:03:29 - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

10/05/2017 22:03:29 - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

10/05/2017 22:03:29 - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.admin.pkgdef

10/05/2017 22:03:29 - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions;C:\Users\Paulo\AppData\Local\Microsoft\VisualStudio\15.0_cecbe2cf\Extensions

10/05/2017 22:03:29 - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions

10/05/2017 22:03:29 - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
10/05/2017 22:03:29 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
10/05/2017 22:03:29 - PKGDEF Information: User extensions enabled by setting, Path: HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\15.0_cecbe2cf\ExtensionManager\EnableAdminExtensions

10/05/2017 22:03:29 - PKGDEF Information: PkgDefCache flags, PKGDEF: 7001
10/05/2017 22:03:29 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
10/05/2017 22:03:29 - PKGDEF Information: PkgDef cache is current.
10/05/2017 22:03:29 - PKGDEF Information: PkgDefManagement startup complete
10/05/2017 22:03:31 - The extension will be upgraded from version 2.2.0.10.
10/05/2017 22:04:21 - The following target products have been selected...
10/05/2017 22:04:21 - 	Microsoft Visual Studio Enterprise 2017
10/05/2017 22:04:21 - 
10/05/2017 22:04:22 - Beginning to install extension to Microsoft Visual Studio Enterprise 2017...
10/05/2017 22:04:22 - Upgrading 'GitHub Extension for Visual Studio', version 2.2.0.10 to version 2.2.0.11.
10/05/2017 22:04:23 - VSIX TaskScheduler: VSIX Auto Updatetask does not exist.
10/05/2017 22:04:23 - VSIX TaskScheduler: VSIX Auto Updatetask has been successfully created.
10/05/2017 22:04:31 - Package Microsoft.Windows.UniversalCRT.Msu.8 is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.2,6.3)'.
10/05/2017 22:04:31 - Package Microsoft.Windows.UniversalCRT.Msu.81 is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.3,6.4)'.
10/05/2017 22:04:31 - Package Microsoft.Net.4.6.FullRedist is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.1.1,6.4)'.
10/05/2017 22:04:31 - Windows Installer found the package 'Microsoft.VisualStudio.Setup.Configuration,version=1.10.80.60812' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:31 - Windows Installer found the package 'Microsoft.VisualStudio.Debugger.Script.Msi,version=15.0.26208.0,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:31 - Package Microsoft.Windows.UniversalCRT.Msu.7 is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.1,6.2)'.
10/05/2017 22:04:31 - Package Microsoft.DiagnosticsHub.KB2882822.Win7 is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.1,6.2)'.
10/05/2017 22:04:31 - Package WebSocket4NetV2 is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.1,6.2)'.
10/05/2017 22:04:31 - Package Microsoft.Net.4.6.1.FullRedist is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.1.1,10.0.10241)'.
10/05/2017 22:04:31 - Windows Installer found the package 'Microsoft.Icecap.Collection.Msi.Resources,version=15.0.26208.0,language=en-US' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:31 - Windows Installer found the package 'Microsoft.Icecap.Collection.Msi,version=15.0.26208.0' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:31 - Windows Installer found the package 'Microsoft.DiagnosticsHub.Collection.Service,version=15.0.26208.0,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:31 - Windows Installer found the package 'Microsoft.VisualCpp.CRT.ClickOnce.Msi,version=14.10.25008.0,language=en-US' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:31 - Windows Installer found the package 'Microsoft.VisualStudio.Debugger.ImmersiveActivateHelper.Msi,version=15.0.26208.0' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:31 - Windows Installer found the package 'Microsoft.VisualStudio.Windows.Tools.Msi,version=15.0.26208.0' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:32 - Package Microsoft.Windows.81SDK.Store.DirectX.Msi is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.1,6.3]'.
10/05/2017 22:04:32 - Package Microsoft.Windows.81SDK.Store.DirectX.Msi is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.1,6.3]'.
10/05/2017 22:04:32 - Package Microsoft.Windows.81SDK.Desktop.DirectX.Msi is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.1,6.3]'.
10/05/2017 22:04:32 - Package Microsoft.Windows.81SDK.Desktop.DirectX.Msi is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '[6.1,6.3]'.
10/05/2017 22:04:32 - Windows Installer found the package 'Microsoft.VisualStudio.Debugger.JustInTime.Msi,version=15.0.26208.0,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:32 - Windows Installer found the package 'Microsoft.VisualStudio.WCF.DiagnosticPack.Msi,version=15.0.26208.0' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:32 - Windows Installer found the package 'Microsoft.VisualStudio.Debugger.Wcf.Msi,version=15.0.26208.0,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
10/05/2017 22:04:32 - Package Microsoft.VisualStudio.OfficeDeveloperTools.WindowsIdentityFoundation.Msu is not applicable. Skipping it due to the following reason(s): The current OS Version '10.0.16188.0' is not in the supported version range '(,6.2)'.
10/05/2017 22:05:24 - Install Error : System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CommitInstalledAndUninstalledExtensions(IEnumerable`1 installedExtensions, IEnumerable`1 uninstalledExtensions, IEnumerable`1 packComponentChanges, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

After that, the Team Explorer window shows this:

```
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitHub.Services.VSGitServices". ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GitHub.VisualStudio.GitHubProviderDispatcher.GetService[T]() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\Services\GitHubServiceProvider.cs:line 63
   at GitHub.Services.VSGitServices..ctor(IGitHubServiceProvider serviceProvider) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.TeamFoundation.14\Services\VSGitServices.cs:line 40
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass6_0`2.<CreateStronglyTypedExportFactoryOfTM>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import, RuntimeExport export, Func`3 lazyFactory)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.<CreateValue>b__10_0(RuntimeImport import)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass6_0`2.<CreateStronglyTypedExportFactoryOfTM>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```

**Comment by paulomorgado** [comment]
Same issue as #986

**Comment by paladique** [comment]
@paulomorgado if it's fine with you, we can take this discussion to #986 since I've already replied there. Feel free to reopen if you prefer a separate thread.

**Comment by tinaschrepfer** [comment]
@paulomorgado for the issue where the extension failed to install, could you please run http://aka.ms/vscollect and share the logs with us?  That will help us figure out what went wrong with the install.

**Comment by shana** [comment]
Reopening this so other users can track the issue while we're trying to figure out what's going on.

**Comment by shana** [comment]
For reference: while we're not sure yet what's going on, if you run into this problem please follow the instructions above for collecting logs. You can send them to support@github.com if you prefer not to share them here.

A workaround to this problem is to uninstall the extension first. If you uninstall from the VS Extensions and Updates menu, you will be taken to the VS installer to uninstall the extension from there (since it was originally installed from the VS installer). Once uninstalled, you can install the latest one from the VS gallery via the Extensions and Updates menu.

**Comment by paulomorgado** [comment]
The logs are 1360705 bytes. Do I upload them somewhere?

The extension installs just fine in the preview instance I have on both machines. On the release instance it failed on 15.1 and it's failing on 15.2. It might be related to some extension I might have installed on the release instance and not on the preview instance.

**Comment by tinaschrepfer** [comment]
@paulomorgado can you put it on a OneDrive location or somewhere we can access?  Thank you!

**Comment by paulomorgado** [comment]
Justa sent an e-mail to support@github.com mentioning issues 986 and 987. Please, acknowledge.

**Comment by tinaschrepfer** [comment]
@paulomorgado I got the logs from @grokys, thanks!  Trying to narrow down the issue here, can you tell me if you see a folder named "wyhgzaqi.mh1"?  If so, could you spit out the contents of that directory (including full path), and let me know if it's the same instance of VS that the extension update failed?  Thanks for your help!

**Comment by paulomorgado** [comment]
I have no such directory on my systems.

**Comment by paulomorgado** [comment]
By the way. I tried to uninstall the GitHub extensions and it also fails.

**Comment by shana** [comment]
@paulomorgado Ok so we're going to have to get a bit more radical with cleaning up whatever the VS installer did to your system that's causing this.

If you're running multiple flavors of VS 2017, then you probably have one or more of the following directories on your system:

`C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions`
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions`

Shutdown all instances of VS and try the following:

Go to each one and do a search for `GitHub.VisualStudio.dll`. All the directories that contain a file with that name are installations of GHfVS. Delete the directories that have that file (they have random names like `0sfcmtxg.f4t`).

Once you've removed all the directories, open a developer command prompt *as administrator* for each of the VS installations (right click on the developer command prompt short and click `Run as administrator`, and run:

`devenv /setup`

This command will take a while to run. After you've done this to all your VS 2017 installations, run VS so that the catalog is rebuilt. If things go well, the extension will no longer be installed and you should not have errors in the Team Explorer area. After that, you should have no problems installing the extension from the Extensions and Updates menu in VS.

**Comment by paulomorgado** [comment]
Strangely enough, I have 2 of those for the release instance and one for the preview:

```
C:\Program Files (x86)\Microsoft Visual Studio> dir -Path . -Filter GitHub.VisualStudio.dll -Recurse


    Directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\cwpzmjov.0yk


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       02/05/2017     17:20         274944 GitHub.VisualStudio.dll


    Directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\dphzvrzq.gnr


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/05/2017     08:53         274944 GitHub.VisualStudio.dll


    Directory: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\dphzvrzq.gnr


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/05/2017     09:11         274944 GitHub.VisualStudio.dll

```

**Comment by paulomorgado** [comment]
I decided to just delete the directories for the release instance and normally start VS2017.

VS complained a bit, but the extension was now available for installation and installed without any issues. Except that it didn't stick.

I ended up running ``devenv /setup** (nothing happened) and **devenv** again to install the extension, but still nothing. Do I need to remove that DLL for all instances?

**Comment by shana** [comment]
@paulomorgado You have two versions in the release instance because you likely installed 2.2.0.10 from the VS installer and then updated to 2.2.0.11 via the gallery, and VS often doesn't delete old versions - and if the old installation failed to uninstall but the new one got installed somehow, then that could cause the problems you got. It's also possible that the installations on the previews are messing up the release VS, or vice versa.

If the preview instances are working properly, perhaps uninstalling the extensions from them will fix the release instance, so it's probably worth trying that.

If it doesn't, you should probably delete all the directories that you have with the extension, just to get things back to a sane state. DO NOT run VS afterwards until you **first** run `devenv /setup` on each of the VS versions you delete the extensions from. Just running VS will not fix whatever catalog corruption might be going on there, and might make things worse.

**Comment by tinaschrepfer** [comment]
@paulomorgado, I would also add that you should remove the GitHub extension for Visual Studio from VS Installer prior to removing the DLLs to make sure you don't corrupt the setup state.  To do so, go to VS Installer, and then the Individual Component tab, unselect "GitHub extension for Visual Studio", and then click Modify.

**Comment by paulomorgado** [comment]
Yeah, @tinaschrepfer! That's what I was missing. Otherwise, the extension installer happily reports success and does nothing.

**Comment by Grumpelumpf** [comment]
@shana post works great and fixed to problem. thx. 

For some reason, there was 2 installations of GitHub Extension in my single Visual Studio 2017 installation.

**Comment by grokys** [comment]
I'm going to close this issue as it looks like the original issue has been fixed. For anyone having these problems in future, please look at https://github.com/github/VisualStudio/issues/1394.
