### ISSUE TITLE
Visual Studio blows up when a file is opened in an empty solution

### ISSUE THREAD

**Issue by jcansdale** [github/VisualStudio#994]
- GitHub Extension for Visual Studio version: 2.2.0.11
- Visual Studio version: 2015

Exception message:
```
System.InvalidOperationException was unhandled
Message: An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
Additional information: The host '' is not a valid host
```

![image](https://cloud.githubusercontent.com/assets/11719160/26024712/23057996-37cf-11e7-8cd1-9d217e73d3a4.png)

## Repro

1. Open Visual Studio
2. Select the Team Explorer window
3. Open a text file using `File > Open > File...`

![image](https://cloud.githubusercontent.com/assets/11719160/26024789/1a56a886-37d1-11e7-8f4d-2797bd62ac97.png)

It's doing this in my Experimental instance of VS but not my regular one. 😕

**Comment by jcansdale** [comment]
I think this exception trace might be related:

```
   at GitHub.VisualStudio.GitHubProviderDispatcher.GetService[T,Ret]() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.VisualStudio\Services\GitHubServiceProvider.cs:line 67
   at GitHub.Services.TeamExplorerServices.IsNotificationVisible(Guid guid) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.TeamFoundation.14\Services\TeamExplorerServices.cs:line 83
   at GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection.IsGitToolsMessageVisible() in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.TeamFoundation.14\Home\GitHubHomeSection.cs:line 79
   at GitHub.VisualStudio.TeamExplorer.Home.GitHubHomeSection.<>c__DisplayClass6_0.<.ctor>b__1(Object s, EventArgs e) in Y:\jenkins\workspace\GitHub for Visual Studio speakeasy jenkinskeep\src\GitHub.TeamFoundation.14\Home\GitHubHomeSection.cs:line 67
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by jcansdale** [comment]
The issue might be here:
https://github.com/github/VisualStudio/blob/d253ba3b48b092bdf029be5373a7d21128dd8ebe/src/GitHub.InlineReviews/InlineReviewsPackage.cs#L35

**Comment by grokys** [comment]
@jcansdale just tried to repro this on master but couldn't. Is it still happening for you?

**Comment by jcansdale** [comment]
Haven't seen this for a while. Closing.
